// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin.sql

package dbq

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const adminAcceptInvitation = `-- name: AdminAcceptInvitation :one
UPDATE admin_invitations
SET accepted_at = now(),
    accepted_by_admin_user_id = $3
WHERE email = $1
  AND token_hash = $2
  AND accepted_at IS NULL
  AND deleted_at IS NULL
  AND expires_at > now()
RETURNING
    id,
    email,
    expires_at,
    accepted_at,
    deleted_at,
    created_at
`

type AdminAcceptInvitationParams struct {
	Email                 string      `json:"email"`
	TokenHash             string      `json:"token_hash"`
	AcceptedByAdminUserID pgtype.UUID `json:"accepted_by_admin_user_id"`
}

type AdminAcceptInvitationRow struct {
	ID         uuid.UUID          `json:"id"`
	Email      string             `json:"email"`
	ExpiresAt  time.Time          `json:"expires_at"`
	AcceptedAt pgtype.Timestamptz `json:"accepted_at"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt  time.Time          `json:"created_at"`
}

func (q *Queries) AdminAcceptInvitation(ctx context.Context, arg AdminAcceptInvitationParams) (AdminAcceptInvitationRow, error) {
	row := q.db.QueryRow(ctx, adminAcceptInvitation, arg.Email, arg.TokenHash, arg.AcceptedByAdminUserID)
	var i AdminAcceptInvitationRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const adminAcknowledgeRejectedEvents = `-- name: AdminAcknowledgeRejectedEvents :exec
INSERT INTO project_rejection_acks (project_id, acknowledged_at)
VALUES ($1, now())
ON CONFLICT (project_id) DO UPDATE SET acknowledged_at = now()
`

func (q *Queries) AdminAcknowledgeRejectedEvents(ctx context.Context, projectID uuid.UUID) error {
	_, err := q.db.Exec(ctx, adminAcknowledgeRejectedEvents, projectID)
	return err
}

const adminCountActiveRejectionGroups = `-- name: AdminCountActiveRejectionGroups :one
SELECT count(*)::bigint
FROM (
    SELECT re.event_type, re.reason_code, re.game_version
    FROM rejected_events re
    WHERE re.project_id = $1
    GROUP BY re.event_type, re.reason_code, re.game_version
    HAVING max(re.created_at) >= now() - interval '24 hours'
       AND max(re.created_at) > COALESCE(
            (SELECT acknowledged_at FROM project_rejection_acks WHERE project_id = $1),
            'epoch'::timestamptz
       )
) active_groups
`

func (q *Queries) AdminCountActiveRejectionGroups(ctx context.Context, projectID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, adminCountActiveRejectionGroups, projectID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const adminCountEnabledUsers = `-- name: AdminCountEnabledUsers :one
SELECT count(*)::bigint
FROM admin_users
WHERE enabled = true
`

func (q *Queries) AdminCountEnabledUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, adminCountEnabledUsers)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const adminCountUsers = `-- name: AdminCountUsers :one
SELECT count(*)::bigint
FROM admin_users
`

func (q *Queries) AdminCountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, adminCountUsers)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const adminCreateIngestToken = `-- name: AdminCreateIngestToken :one
INSERT INTO ingest_tokens (
    project_id,
    name,
    token_hash
) VALUES (
    $1, $2, $3
)
RETURNING id, name, enabled, expires_at, last_used_at, created_at
`

type AdminCreateIngestTokenParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Name      string    `json:"name"`
	TokenHash string    `json:"token_hash"`
}

type AdminCreateIngestTokenRow struct {
	ID         uuid.UUID          `json:"id"`
	Name       string             `json:"name"`
	Enabled    bool               `json:"enabled"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt  time.Time          `json:"created_at"`
}

func (q *Queries) AdminCreateIngestToken(ctx context.Context, arg AdminCreateIngestTokenParams) (AdminCreateIngestTokenRow, error) {
	row := q.db.QueryRow(ctx, adminCreateIngestToken, arg.ProjectID, arg.Name, arg.TokenHash)
	var i AdminCreateIngestTokenRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Enabled,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const adminCreateInvitation = `-- name: AdminCreateInvitation :one
INSERT INTO admin_invitations (
    email,
    token_hash,
    created_by_admin_user_id,
    expires_at
) VALUES (
    $1, $2, $3, now() + interval '48 hours'
)
RETURNING
    id,
    email,
    expires_at,
    accepted_at,
    deleted_at,
    created_at
`

type AdminCreateInvitationParams struct {
	Email                string      `json:"email"`
	TokenHash            string      `json:"token_hash"`
	CreatedByAdminUserID pgtype.UUID `json:"created_by_admin_user_id"`
}

type AdminCreateInvitationRow struct {
	ID         uuid.UUID          `json:"id"`
	Email      string             `json:"email"`
	ExpiresAt  time.Time          `json:"expires_at"`
	AcceptedAt pgtype.Timestamptz `json:"accepted_at"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt  time.Time          `json:"created_at"`
}

func (q *Queries) AdminCreateInvitation(ctx context.Context, arg AdminCreateInvitationParams) (AdminCreateInvitationRow, error) {
	row := q.db.QueryRow(ctx, adminCreateInvitation, arg.Email, arg.TokenHash, arg.CreatedByAdminUserID)
	var i AdminCreateInvitationRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const adminCreateReportNote = `-- name: AdminCreateReportNote :one
INSERT INTO report_notes (
    report_id,
    note
) VALUES (
    $1, $2
)
RETURNING id, note, created_at
`

type AdminCreateReportNoteParams struct {
	ReportID uuid.UUID `json:"report_id"`
	Note     string    `json:"note"`
}

type AdminCreateReportNoteRow struct {
	ID        uuid.UUID `json:"id"`
	Note      string    `json:"note"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) AdminCreateReportNote(ctx context.Context, arg AdminCreateReportNoteParams) (AdminCreateReportNoteRow, error) {
	row := q.db.QueryRow(ctx, adminCreateReportNote, arg.ReportID, arg.Note)
	var i AdminCreateReportNoteRow
	err := row.Scan(&i.ID, &i.Note, &i.CreatedAt)
	return i, err
}

const adminCreateUser = `-- name: AdminCreateUser :one
INSERT INTO admin_users (
    email,
    oauth_subject,
    role,
    enabled,
    name,
    picture_url,
    provider,
    last_login_at
) VALUES (
    $1, $2, 'admin', true, $3, $4, $5, now()
)
RETURNING
    id,
    email,
    oauth_subject,
    role,
    enabled,
    name,
    picture_url,
    provider,
    last_login_at,
    created_at,
    updated_at
`

type AdminCreateUserParams struct {
	Email        string      `json:"email"`
	OauthSubject pgtype.Text `json:"oauth_subject"`
	Name         string      `json:"name"`
	PictureUrl   string      `json:"picture_url"`
	Provider     string      `json:"provider"`
}

type AdminCreateUserRow struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	OauthSubject pgtype.Text        `json:"oauth_subject"`
	Role         string             `json:"role"`
	Enabled      bool               `json:"enabled"`
	Name         string             `json:"name"`
	PictureUrl   string             `json:"picture_url"`
	Provider     string             `json:"provider"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
}

func (q *Queries) AdminCreateUser(ctx context.Context, arg AdminCreateUserParams) (AdminCreateUserRow, error) {
	row := q.db.QueryRow(ctx, adminCreateUser,
		arg.Email,
		arg.OauthSubject,
		arg.Name,
		arg.PictureUrl,
		arg.Provider,
	)
	var i AdminCreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.OauthSubject,
		&i.Role,
		&i.Enabled,
		&i.Name,
		&i.PictureUrl,
		&i.Provider,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminDeleteInvitation = `-- name: AdminDeleteInvitation :one
UPDATE admin_invitations
SET deleted_at = now()
WHERE id = $1
  AND accepted_at IS NULL
  AND deleted_at IS NULL
RETURNING
    id,
    email,
    expires_at,
    accepted_at,
    deleted_at,
    created_at
`

type AdminDeleteInvitationRow struct {
	ID         uuid.UUID          `json:"id"`
	Email      string             `json:"email"`
	ExpiresAt  time.Time          `json:"expires_at"`
	AcceptedAt pgtype.Timestamptz `json:"accepted_at"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt  time.Time          `json:"created_at"`
}

func (q *Queries) AdminDeleteInvitation(ctx context.Context, id uuid.UUID) (AdminDeleteInvitationRow, error) {
	row := q.db.QueryRow(ctx, adminDeleteInvitation, id)
	var i AdminDeleteInvitationRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const adminEventTypes = `-- name: AdminEventTypes :many
SELECT
    event_type,
    count(*)::bigint AS event_count,
    max(real_ts)::timestamptz AS last_seen_at,
    (
        SELECT payload
        FROM events sample
        WHERE sample.project_id = e.project_id
          AND sample.event_type = e.event_type
        ORDER BY sample.real_ts DESC
        LIMIT 1
    ) AS sample_payload
FROM events e
WHERE e.project_id = $1
GROUP BY e.project_id, e.event_type
ORDER BY event_count DESC
`

type AdminEventTypesRow struct {
	EventType     string          `json:"event_type"`
	EventCount    int64           `json:"event_count"`
	LastSeenAt    time.Time       `json:"last_seen_at"`
	SamplePayload json.RawMessage `json:"sample_payload"`
}

func (q *Queries) AdminEventTypes(ctx context.Context, projectID uuid.UUID) ([]AdminEventTypesRow, error) {
	rows, err := q.db.Query(ctx, adminEventTypes, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminEventTypesRow{}
	for rows.Next() {
		var i AdminEventTypesRow
		if err := rows.Scan(
			&i.EventType,
			&i.EventCount,
			&i.LastSeenAt,
			&i.SamplePayload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminGetReport = `-- name: AdminGetReport :one
SELECT
    br.id,
    br.report_id,
    br.status,
    br.labels,
    br.mood,
    br.mood_label,
    br.notes_preview,
    br.screenshot_object_key,
    br.screenshot_storage_error,
    br.created_at,
    e.player_id,
    e.real_ts,
    e.game_time,
    e.region_id,
    e.zone_id,
    e.coord_x,
    e.coord_y,
    e.coord_z,
    e.context,
    e.metrics,
    e.dimensions,
    e.payload
FROM bug_reports br
JOIN events e ON e.id = br.event_id
WHERE br.project_id = $1
  AND br.report_id = $2
`

type AdminGetReportParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	ReportID  string    `json:"report_id"`
}

type AdminGetReportRow struct {
	ID                     uuid.UUID       `json:"id"`
	ReportID               string          `json:"report_id"`
	Status                 string          `json:"status"`
	Labels                 []string        `json:"labels"`
	Mood                   int32           `json:"mood"`
	MoodLabel              string          `json:"mood_label"`
	NotesPreview           string          `json:"notes_preview"`
	ScreenshotObjectKey    pgtype.Text     `json:"screenshot_object_key"`
	ScreenshotStorageError pgtype.Text     `json:"screenshot_storage_error"`
	CreatedAt              time.Time       `json:"created_at"`
	PlayerID               uuid.UUID       `json:"player_id"`
	RealTs                 time.Time       `json:"real_ts"`
	GameTime               int64           `json:"game_time"`
	RegionID               string          `json:"region_id"`
	ZoneID                 string          `json:"zone_id"`
	CoordX                 float64         `json:"coord_x"`
	CoordY                 float64         `json:"coord_y"`
	CoordZ                 float64         `json:"coord_z"`
	Context                json.RawMessage `json:"context"`
	Metrics                json.RawMessage `json:"metrics"`
	Dimensions             json.RawMessage `json:"dimensions"`
	Payload                json.RawMessage `json:"payload"`
}

func (q *Queries) AdminGetReport(ctx context.Context, arg AdminGetReportParams) (AdminGetReportRow, error) {
	row := q.db.QueryRow(ctx, adminGetReport, arg.ProjectID, arg.ReportID)
	var i AdminGetReportRow
	err := row.Scan(
		&i.ID,
		&i.ReportID,
		&i.Status,
		&i.Labels,
		&i.Mood,
		&i.MoodLabel,
		&i.NotesPreview,
		&i.ScreenshotObjectKey,
		&i.ScreenshotStorageError,
		&i.CreatedAt,
		&i.PlayerID,
		&i.RealTs,
		&i.GameTime,
		&i.RegionID,
		&i.ZoneID,
		&i.CoordX,
		&i.CoordY,
		&i.CoordZ,
		&i.Context,
		&i.Metrics,
		&i.Dimensions,
		&i.Payload,
	)
	return i, err
}

const adminGetUserByEmail = `-- name: AdminGetUserByEmail :one
SELECT
    id,
    email,
    oauth_subject,
    role,
    enabled,
    name,
    picture_url,
    provider,
    last_login_at,
    created_at,
    updated_at
FROM admin_users
WHERE email = $1
`

type AdminGetUserByEmailRow struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	OauthSubject pgtype.Text        `json:"oauth_subject"`
	Role         string             `json:"role"`
	Enabled      bool               `json:"enabled"`
	Name         string             `json:"name"`
	PictureUrl   string             `json:"picture_url"`
	Provider     string             `json:"provider"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
}

func (q *Queries) AdminGetUserByEmail(ctx context.Context, email string) (AdminGetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, adminGetUserByEmail, email)
	var i AdminGetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.OauthSubject,
		&i.Role,
		&i.Enabled,
		&i.Name,
		&i.PictureUrl,
		&i.Provider,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminGetUserByID = `-- name: AdminGetUserByID :one
SELECT
    id,
    email,
    oauth_subject,
    role,
    enabled,
    name,
    picture_url,
    provider,
    last_login_at,
    created_at,
    updated_at
FROM admin_users
WHERE id = $1
`

type AdminGetUserByIDRow struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	OauthSubject pgtype.Text        `json:"oauth_subject"`
	Role         string             `json:"role"`
	Enabled      bool               `json:"enabled"`
	Name         string             `json:"name"`
	PictureUrl   string             `json:"picture_url"`
	Provider     string             `json:"provider"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
}

func (q *Queries) AdminGetUserByID(ctx context.Context, id uuid.UUID) (AdminGetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, adminGetUserByID, id)
	var i AdminGetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.OauthSubject,
		&i.Role,
		&i.Enabled,
		&i.Name,
		&i.PictureUrl,
		&i.Provider,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminGetUserBySubject = `-- name: AdminGetUserBySubject :one
SELECT
    id,
    email,
    oauth_subject,
    role,
    enabled,
    name,
    picture_url,
    provider,
    last_login_at,
    created_at,
    updated_at
FROM admin_users
WHERE oauth_subject = $1
`

type AdminGetUserBySubjectRow struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	OauthSubject pgtype.Text        `json:"oauth_subject"`
	Role         string             `json:"role"`
	Enabled      bool               `json:"enabled"`
	Name         string             `json:"name"`
	PictureUrl   string             `json:"picture_url"`
	Provider     string             `json:"provider"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
}

func (q *Queries) AdminGetUserBySubject(ctx context.Context, oauthSubject pgtype.Text) (AdminGetUserBySubjectRow, error) {
	row := q.db.QueryRow(ctx, adminGetUserBySubject, oauthSubject)
	var i AdminGetUserBySubjectRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.OauthSubject,
		&i.Role,
		&i.Enabled,
		&i.Name,
		&i.PictureUrl,
		&i.Provider,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminListActiveInvitations = `-- name: AdminListActiveInvitations :many
SELECT
    i.id,
    i.email,
    i.expires_at,
    i.created_at,
    creator.email AS created_by_email
FROM admin_invitations i
LEFT JOIN admin_users creator ON creator.id = i.created_by_admin_user_id
WHERE i.accepted_at IS NULL
  AND i.deleted_at IS NULL
  AND i.expires_at > now()
ORDER BY i.created_at DESC
`

type AdminListActiveInvitationsRow struct {
	ID             uuid.UUID   `json:"id"`
	Email          string      `json:"email"`
	ExpiresAt      time.Time   `json:"expires_at"`
	CreatedAt      time.Time   `json:"created_at"`
	CreatedByEmail pgtype.Text `json:"created_by_email"`
}

func (q *Queries) AdminListActiveInvitations(ctx context.Context) ([]AdminListActiveInvitationsRow, error) {
	rows, err := q.db.Query(ctx, adminListActiveInvitations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListActiveInvitationsRow{}
	for rows.Next() {
		var i AdminListActiveInvitationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.CreatedByEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListAgentAuthorizations = `-- name: AdminListAgentAuthorizations :many
SELECT
    aa.id,
    aa.client_id,
    aa.client_name,
    aa.created_by_admin_user_id,
    creator.email AS created_by_email,
    aa.all_projects,
    aa.scopes,
    aa.enabled,
    aa.expires_at,
    aa.activated_at,
    aa.last_used_at,
    aa.created_at,
    aa.updated_at,
    COALESCE(
        (
            SELECT jsonb_agg(p.project_key ORDER BY p.project_key)
            FROM agent_authorization_projects aap
            JOIN projects p ON p.id = aap.project_id
            WHERE aap.agent_authorization_id = aa.id
        ),
        '[]'::jsonb
    )::jsonb AS project_keys
FROM agent_authorizations aa
LEFT JOIN admin_users creator ON creator.id = aa.created_by_admin_user_id
ORDER BY aa.created_at DESC
`

type AdminListAgentAuthorizationsRow struct {
	ID                   uuid.UUID          `json:"id"`
	ClientID             string             `json:"client_id"`
	ClientName           string             `json:"client_name"`
	CreatedByAdminUserID pgtype.UUID        `json:"created_by_admin_user_id"`
	CreatedByEmail       pgtype.Text        `json:"created_by_email"`
	AllProjects          bool               `json:"all_projects"`
	Scopes               []string           `json:"scopes"`
	Enabled              bool               `json:"enabled"`
	ExpiresAt            time.Time          `json:"expires_at"`
	ActivatedAt          pgtype.Timestamptz `json:"activated_at"`
	LastUsedAt           pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt            time.Time          `json:"created_at"`
	UpdatedAt            time.Time          `json:"updated_at"`
	ProjectKeys          json.RawMessage    `json:"project_keys"`
}

func (q *Queries) AdminListAgentAuthorizations(ctx context.Context) ([]AdminListAgentAuthorizationsRow, error) {
	rows, err := q.db.Query(ctx, adminListAgentAuthorizations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListAgentAuthorizationsRow{}
	for rows.Next() {
		var i AdminListAgentAuthorizationsRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.ClientName,
			&i.CreatedByAdminUserID,
			&i.CreatedByEmail,
			&i.AllProjects,
			&i.Scopes,
			&i.Enabled,
			&i.ExpiresAt,
			&i.ActivatedAt,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProjectKeys,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListEvents = `-- name: AdminListEvents :many
SELECT
    id,
    player_id,
    event_type,
    real_ts,
    game_time,
    region_id,
    zone_id,
    coord_x,
    coord_y,
    coord_z,
    game_version,
    build_channel,
    commit_sha,
    platform,
    context,
    metrics,
    dimensions,
    payload,
    event_json,
    COALESCE(
        (
            SELECT jsonb_object_agg(
                ef.field_key,
                CASE ef.value_type
                    WHEN 'number' THEN to_jsonb(ef.number_value)
                    WHEN 'bool' THEN to_jsonb(ef.bool_value)
                    ELSE to_jsonb(ef.string_value)
                END
            )
            FROM event_fields ef
            WHERE ef.event_id = events.id
        ),
        '{}'::jsonb
    )::jsonb AS fields,
    validation_errors
FROM events
WHERE events.project_id = $1
  AND ($6::text IS NULL OR event_type = $6)
  AND ($7::text IS NULL OR region_id = $7)
  AND ($8::text IS NULL OR zone_id = $8)
  AND ($9::uuid IS NULL OR player_id = $9::uuid)
  AND ($10::text IS NULL OR game_version = $10)
  AND ($11::text IS NULL OR build_channel = $11)
  AND real_ts >= $2
  AND real_ts <= $3
ORDER BY real_ts DESC
LIMIT $4
OFFSET $5
`

type AdminListEventsParams struct {
	ProjectID    uuid.UUID   `json:"project_id"`
	RealTs       time.Time   `json:"real_ts"`
	RealTs_2     time.Time   `json:"real_ts_2"`
	Limit        int32       `json:"limit"`
	Offset       int32       `json:"offset"`
	EventType    pgtype.Text `json:"event_type"`
	RegionID     pgtype.Text `json:"region_id"`
	ZoneID       pgtype.Text `json:"zone_id"`
	PlayerID     pgtype.UUID `json:"player_id"`
	GameVersion  pgtype.Text `json:"game_version"`
	BuildChannel pgtype.Text `json:"build_channel"`
}

type AdminListEventsRow struct {
	ID               uuid.UUID       `json:"id"`
	PlayerID         uuid.UUID       `json:"player_id"`
	EventType        string          `json:"event_type"`
	RealTs           time.Time       `json:"real_ts"`
	GameTime         int64           `json:"game_time"`
	RegionID         string          `json:"region_id"`
	ZoneID           string          `json:"zone_id"`
	CoordX           float64         `json:"coord_x"`
	CoordY           float64         `json:"coord_y"`
	CoordZ           float64         `json:"coord_z"`
	GameVersion      string          `json:"game_version"`
	BuildChannel     string          `json:"build_channel"`
	CommitSHA        string          `json:"commit_sha"`
	Platform         string          `json:"platform"`
	Context          json.RawMessage `json:"context"`
	Metrics          json.RawMessage `json:"metrics"`
	Dimensions       json.RawMessage `json:"dimensions"`
	Payload          json.RawMessage `json:"payload"`
	EventJson        json.RawMessage `json:"event_json"`
	Fields           json.RawMessage `json:"fields"`
	ValidationErrors json.RawMessage `json:"validation_errors"`
}

func (q *Queries) AdminListEvents(ctx context.Context, arg AdminListEventsParams) ([]AdminListEventsRow, error) {
	rows, err := q.db.Query(ctx, adminListEvents,
		arg.ProjectID,
		arg.RealTs,
		arg.RealTs_2,
		arg.Limit,
		arg.Offset,
		arg.EventType,
		arg.RegionID,
		arg.ZoneID,
		arg.PlayerID,
		arg.GameVersion,
		arg.BuildChannel,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListEventsRow{}
	for rows.Next() {
		var i AdminListEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.PlayerID,
			&i.EventType,
			&i.RealTs,
			&i.GameTime,
			&i.RegionID,
			&i.ZoneID,
			&i.CoordX,
			&i.CoordY,
			&i.CoordZ,
			&i.GameVersion,
			&i.BuildChannel,
			&i.CommitSHA,
			&i.Platform,
			&i.Context,
			&i.Metrics,
			&i.Dimensions,
			&i.Payload,
			&i.EventJson,
			&i.Fields,
			&i.ValidationErrors,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListEventsByField = `-- name: AdminListEventsByField :many
SELECT
    events.id,
    player_id,
    event_type,
    real_ts,
    game_time,
    region_id,
    zone_id,
    coord_x,
    coord_y,
    coord_z,
    game_version,
    build_channel,
    commit_sha,
    platform,
    context,
    metrics,
    dimensions,
    payload,
    event_json,
    COALESCE(
        (
            SELECT jsonb_object_agg(
                ef.field_key,
                CASE ef.value_type
                    WHEN 'number' THEN to_jsonb(ef.number_value)
                    WHEN 'bool' THEN to_jsonb(ef.bool_value)
                    ELSE to_jsonb(ef.string_value)
                END
            )
            FROM event_fields ef
            WHERE ef.event_id = events.id
        ),
        '{}'::jsonb
    )::jsonb AS fields,
    validation_errors
FROM event_fields filter_field
JOIN events ON events.id = filter_field.event_id
WHERE filter_field.project_id = $1
  AND filter_field.field_key = $6
  AND filter_field.value_type = $7
  AND (
      NOT $8::bool
      OR (filter_field.value_type = 'string' AND filter_field.string_value = $9::text)
      OR (filter_field.value_type = 'number' AND filter_field.number_value = $10::double precision)
      OR (filter_field.value_type = 'bool' AND filter_field.bool_value = $11::boolean)
  )
  AND events.project_id = $1
  AND ($12::text IS NULL OR event_type = $12)
  AND ($13::text IS NULL OR region_id = $13)
  AND ($14::text IS NULL OR zone_id = $14)
  AND ($15::uuid IS NULL OR player_id = $15::uuid)
  AND ($16::text IS NULL OR game_version = $16)
  AND ($17::text IS NULL OR build_channel = $17)
  AND real_ts >= $2
  AND real_ts <= $3
ORDER BY real_ts DESC
LIMIT $4
OFFSET $5
`

type AdminListEventsByFieldParams struct {
	ProjectID        uuid.UUID   `json:"project_id"`
	RealTs           time.Time   `json:"real_ts"`
	RealTs_2         time.Time   `json:"real_ts_2"`
	Limit            int32       `json:"limit"`
	Offset           int32       `json:"offset"`
	FieldKey         string      `json:"field_key"`
	FieldValueType   string      `json:"field_value_type"`
	HasFieldValue    bool        `json:"has_field_value"`
	FieldStringValue string      `json:"field_string_value"`
	FieldNumberValue float64     `json:"field_number_value"`
	FieldBoolValue   bool        `json:"field_bool_value"`
	EventType        pgtype.Text `json:"event_type"`
	RegionID         pgtype.Text `json:"region_id"`
	ZoneID           pgtype.Text `json:"zone_id"`
	PlayerID         pgtype.UUID `json:"player_id"`
	GameVersion      pgtype.Text `json:"game_version"`
	BuildChannel     pgtype.Text `json:"build_channel"`
}

type AdminListEventsByFieldRow struct {
	ID               uuid.UUID       `json:"id"`
	PlayerID         uuid.UUID       `json:"player_id"`
	EventType        string          `json:"event_type"`
	RealTs           time.Time       `json:"real_ts"`
	GameTime         int64           `json:"game_time"`
	RegionID         string          `json:"region_id"`
	ZoneID           string          `json:"zone_id"`
	CoordX           float64         `json:"coord_x"`
	CoordY           float64         `json:"coord_y"`
	CoordZ           float64         `json:"coord_z"`
	GameVersion      string          `json:"game_version"`
	BuildChannel     string          `json:"build_channel"`
	CommitSHA        string          `json:"commit_sha"`
	Platform         string          `json:"platform"`
	Context          json.RawMessage `json:"context"`
	Metrics          json.RawMessage `json:"metrics"`
	Dimensions       json.RawMessage `json:"dimensions"`
	Payload          json.RawMessage `json:"payload"`
	EventJson        json.RawMessage `json:"event_json"`
	Fields           json.RawMessage `json:"fields"`
	ValidationErrors json.RawMessage `json:"validation_errors"`
}

func (q *Queries) AdminListEventsByField(ctx context.Context, arg AdminListEventsByFieldParams) ([]AdminListEventsByFieldRow, error) {
	rows, err := q.db.Query(ctx, adminListEventsByField,
		arg.ProjectID,
		arg.RealTs,
		arg.RealTs_2,
		arg.Limit,
		arg.Offset,
		arg.FieldKey,
		arg.FieldValueType,
		arg.HasFieldValue,
		arg.FieldStringValue,
		arg.FieldNumberValue,
		arg.FieldBoolValue,
		arg.EventType,
		arg.RegionID,
		arg.ZoneID,
		arg.PlayerID,
		arg.GameVersion,
		arg.BuildChannel,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListEventsByFieldRow{}
	for rows.Next() {
		var i AdminListEventsByFieldRow
		if err := rows.Scan(
			&i.ID,
			&i.PlayerID,
			&i.EventType,
			&i.RealTs,
			&i.GameTime,
			&i.RegionID,
			&i.ZoneID,
			&i.CoordX,
			&i.CoordY,
			&i.CoordZ,
			&i.GameVersion,
			&i.BuildChannel,
			&i.CommitSHA,
			&i.Platform,
			&i.Context,
			&i.Metrics,
			&i.Dimensions,
			&i.Payload,
			&i.EventJson,
			&i.Fields,
			&i.ValidationErrors,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListIngestTokens = `-- name: AdminListIngestTokens :many
SELECT
    id,
    name,
    enabled,
    expires_at,
    last_used_at,
    created_at
FROM ingest_tokens
WHERE project_id = $1
ORDER BY created_at DESC
`

type AdminListIngestTokensRow struct {
	ID         uuid.UUID          `json:"id"`
	Name       string             `json:"name"`
	Enabled    bool               `json:"enabled"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt  time.Time          `json:"created_at"`
}

func (q *Queries) AdminListIngestTokens(ctx context.Context, projectID uuid.UUID) ([]AdminListIngestTokensRow, error) {
	rows, err := q.db.Query(ctx, adminListIngestTokens, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListIngestTokensRow{}
	for rows.Next() {
		var i AdminListIngestTokensRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Enabled,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListProjects = `-- name: AdminListProjects :many
SELECT
    project_key,
    display_name,
    validation_mode,
    created_at,
    updated_at
FROM projects
ORDER BY display_name ASC, project_key ASC
`

type AdminListProjectsRow struct {
	ProjectKey     string    `json:"project_key"`
	DisplayName    string    `json:"display_name"`
	ValidationMode string    `json:"validation_mode"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

func (q *Queries) AdminListProjects(ctx context.Context) ([]AdminListProjectsRow, error) {
	rows, err := q.db.Query(ctx, adminListProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListProjectsRow{}
	for rows.Next() {
		var i AdminListProjectsRow
		if err := rows.Scan(
			&i.ProjectKey,
			&i.DisplayName,
			&i.ValidationMode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListReportNotes = `-- name: AdminListReportNotes :many
SELECT
    id,
    note,
    created_at
FROM report_notes
WHERE report_id = $1
ORDER BY created_at DESC
`

type AdminListReportNotesRow struct {
	ID        uuid.UUID `json:"id"`
	Note      string    `json:"note"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) AdminListReportNotes(ctx context.Context, reportID uuid.UUID) ([]AdminListReportNotesRow, error) {
	rows, err := q.db.Query(ctx, adminListReportNotes, reportID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListReportNotesRow{}
	for rows.Next() {
		var i AdminListReportNotesRow
		if err := rows.Scan(&i.ID, &i.Note, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListReports = `-- name: AdminListReports :many
SELECT
    br.id,
    br.report_id,
    br.status,
    br.labels,
    br.mood,
    br.mood_label,
    br.notes_preview,
    br.screenshot_object_key,
    br.created_at,
    e.player_id,
    e.real_ts,
    e.game_time,
    e.region_id,
    e.zone_id,
    e.context,
    e.metrics,
    e.dimensions,
    e.payload
FROM bug_reports br
JOIN events e ON e.id = br.event_id
WHERE br.project_id = $1
  AND ($4::text IS NULL OR br.status = $4)
ORDER BY br.created_at DESC
LIMIT $2
OFFSET $3
`

type AdminListReportsParams struct {
	ProjectID uuid.UUID   `json:"project_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
	Status    pgtype.Text `json:"status"`
}

type AdminListReportsRow struct {
	ID                  uuid.UUID       `json:"id"`
	ReportID            string          `json:"report_id"`
	Status              string          `json:"status"`
	Labels              []string        `json:"labels"`
	Mood                int32           `json:"mood"`
	MoodLabel           string          `json:"mood_label"`
	NotesPreview        string          `json:"notes_preview"`
	ScreenshotObjectKey pgtype.Text     `json:"screenshot_object_key"`
	CreatedAt           time.Time       `json:"created_at"`
	PlayerID            uuid.UUID       `json:"player_id"`
	RealTs              time.Time       `json:"real_ts"`
	GameTime            int64           `json:"game_time"`
	RegionID            string          `json:"region_id"`
	ZoneID              string          `json:"zone_id"`
	Context             json.RawMessage `json:"context"`
	Metrics             json.RawMessage `json:"metrics"`
	Dimensions          json.RawMessage `json:"dimensions"`
	Payload             json.RawMessage `json:"payload"`
}

func (q *Queries) AdminListReports(ctx context.Context, arg AdminListReportsParams) ([]AdminListReportsRow, error) {
	rows, err := q.db.Query(ctx, adminListReports,
		arg.ProjectID,
		arg.Limit,
		arg.Offset,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListReportsRow{}
	for rows.Next() {
		var i AdminListReportsRow
		if err := rows.Scan(
			&i.ID,
			&i.ReportID,
			&i.Status,
			&i.Labels,
			&i.Mood,
			&i.MoodLabel,
			&i.NotesPreview,
			&i.ScreenshotObjectKey,
			&i.CreatedAt,
			&i.PlayerID,
			&i.RealTs,
			&i.GameTime,
			&i.RegionID,
			&i.ZoneID,
			&i.Context,
			&i.Metrics,
			&i.Dimensions,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListReportsByLabel = `-- name: AdminListReportsByLabel :many
SELECT
    br.id,
    br.report_id,
    br.status,
    br.labels,
    br.mood,
    br.mood_label,
    br.notes_preview,
    br.screenshot_object_key,
    br.created_at,
    e.player_id,
    e.real_ts,
    e.game_time,
    e.region_id,
    e.zone_id,
    e.context,
    e.metrics,
    e.dimensions,
    e.payload
FROM bug_reports br
JOIN events e ON e.id = br.event_id
WHERE br.project_id = $1
  AND br.labels @> ARRAY[$4::text]
  AND ($5::text IS NULL OR br.status = $5)
ORDER BY br.created_at DESC
LIMIT $2
OFFSET $3
`

type AdminListReportsByLabelParams struct {
	ProjectID uuid.UUID   `json:"project_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
	Label     string      `json:"label"`
	Status    pgtype.Text `json:"status"`
}

type AdminListReportsByLabelRow struct {
	ID                  uuid.UUID       `json:"id"`
	ReportID            string          `json:"report_id"`
	Status              string          `json:"status"`
	Labels              []string        `json:"labels"`
	Mood                int32           `json:"mood"`
	MoodLabel           string          `json:"mood_label"`
	NotesPreview        string          `json:"notes_preview"`
	ScreenshotObjectKey pgtype.Text     `json:"screenshot_object_key"`
	CreatedAt           time.Time       `json:"created_at"`
	PlayerID            uuid.UUID       `json:"player_id"`
	RealTs              time.Time       `json:"real_ts"`
	GameTime            int64           `json:"game_time"`
	RegionID            string          `json:"region_id"`
	ZoneID              string          `json:"zone_id"`
	Context             json.RawMessage `json:"context"`
	Metrics             json.RawMessage `json:"metrics"`
	Dimensions          json.RawMessage `json:"dimensions"`
	Payload             json.RawMessage `json:"payload"`
}

func (q *Queries) AdminListReportsByLabel(ctx context.Context, arg AdminListReportsByLabelParams) ([]AdminListReportsByLabelRow, error) {
	rows, err := q.db.Query(ctx, adminListReportsByLabel,
		arg.ProjectID,
		arg.Limit,
		arg.Offset,
		arg.Label,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListReportsByLabelRow{}
	for rows.Next() {
		var i AdminListReportsByLabelRow
		if err := rows.Scan(
			&i.ID,
			&i.ReportID,
			&i.Status,
			&i.Labels,
			&i.Mood,
			&i.MoodLabel,
			&i.NotesPreview,
			&i.ScreenshotObjectKey,
			&i.CreatedAt,
			&i.PlayerID,
			&i.RealTs,
			&i.GameTime,
			&i.RegionID,
			&i.ZoneID,
			&i.Context,
			&i.Metrics,
			&i.Dimensions,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListUsers = `-- name: AdminListUsers :many
SELECT
    id,
    email,
    oauth_subject,
    role,
    enabled,
    name,
    picture_url,
    provider,
    last_login_at,
    created_at,
    updated_at
FROM admin_users
ORDER BY email ASC
`

type AdminListUsersRow struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	OauthSubject pgtype.Text        `json:"oauth_subject"`
	Role         string             `json:"role"`
	Enabled      bool               `json:"enabled"`
	Name         string             `json:"name"`
	PictureUrl   string             `json:"picture_url"`
	Provider     string             `json:"provider"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
}

func (q *Queries) AdminListUsers(ctx context.Context) ([]AdminListUsersRow, error) {
	rows, err := q.db.Query(ctx, adminListUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListUsersRow{}
	for rows.Next() {
		var i AdminListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.OauthSubject,
			&i.Role,
			&i.Enabled,
			&i.Name,
			&i.PictureUrl,
			&i.Provider,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminPlayerTrace = `-- name: AdminPlayerTrace :many
SELECT
    id,
    event_type,
    real_ts,
    game_time,
    region_id,
    zone_id,
    coord_x,
    coord_y,
    coord_z,
    context,
    metrics,
    dimensions,
    COALESCE(
        (
            SELECT jsonb_object_agg(
                ef.field_key,
                CASE ef.value_type
                    WHEN 'number' THEN to_jsonb(ef.number_value)
                    WHEN 'bool' THEN to_jsonb(ef.bool_value)
                    ELSE to_jsonb(ef.string_value)
                END
            )
            FROM event_fields ef
            WHERE ef.event_id = events.id
        ),
        '{}'::jsonb
    )::jsonb AS fields,
    payload
FROM events
WHERE events.project_id = $1
  AND player_id = $2
ORDER BY game_time ASC
LIMIT $3
`

type AdminPlayerTraceParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	PlayerID  uuid.UUID `json:"player_id"`
	Limit     int32     `json:"limit"`
}

type AdminPlayerTraceRow struct {
	ID         uuid.UUID       `json:"id"`
	EventType  string          `json:"event_type"`
	RealTs     time.Time       `json:"real_ts"`
	GameTime   int64           `json:"game_time"`
	RegionID   string          `json:"region_id"`
	ZoneID     string          `json:"zone_id"`
	CoordX     float64         `json:"coord_x"`
	CoordY     float64         `json:"coord_y"`
	CoordZ     float64         `json:"coord_z"`
	Context    json.RawMessage `json:"context"`
	Metrics    json.RawMessage `json:"metrics"`
	Dimensions json.RawMessage `json:"dimensions"`
	Fields     json.RawMessage `json:"fields"`
	Payload    json.RawMessage `json:"payload"`
}

func (q *Queries) AdminPlayerTrace(ctx context.Context, arg AdminPlayerTraceParams) ([]AdminPlayerTraceRow, error) {
	rows, err := q.db.Query(ctx, adminPlayerTrace, arg.ProjectID, arg.PlayerID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminPlayerTraceRow{}
	for rows.Next() {
		var i AdminPlayerTraceRow
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.RealTs,
			&i.GameTime,
			&i.RegionID,
			&i.ZoneID,
			&i.CoordX,
			&i.CoordY,
			&i.CoordZ,
			&i.Context,
			&i.Metrics,
			&i.Dimensions,
			&i.Fields,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminProjectSettings = `-- name: AdminProjectSettings :one
SELECT
    id,
    project_key,
    display_name,
    validation_mode,
    ingest_config,
    retention_config,
    map_config,
    report_config,
    event_groups,
    query_fields,
    funnels
FROM projects
WHERE project_key = $1
`

type AdminProjectSettingsRow struct {
	ID              uuid.UUID       `json:"id"`
	ProjectKey      string          `json:"project_key"`
	DisplayName     string          `json:"display_name"`
	ValidationMode  string          `json:"validation_mode"`
	IngestConfig    json.RawMessage `json:"ingest_config"`
	RetentionConfig json.RawMessage `json:"retention_config"`
	MapConfig       json.RawMessage `json:"map_config"`
	ReportConfig    json.RawMessage `json:"report_config"`
	EventGroups     json.RawMessage `json:"event_groups"`
	QueryFields     json.RawMessage `json:"query_fields"`
	Funnels         json.RawMessage `json:"funnels"`
}

func (q *Queries) AdminProjectSettings(ctx context.Context, projectKey string) (AdminProjectSettingsRow, error) {
	row := q.db.QueryRow(ctx, adminProjectSettings, projectKey)
	var i AdminProjectSettingsRow
	err := row.Scan(
		&i.ID,
		&i.ProjectKey,
		&i.DisplayName,
		&i.ValidationMode,
		&i.IngestConfig,
		&i.RetentionConfig,
		&i.MapConfig,
		&i.ReportConfig,
		&i.EventGroups,
		&i.QueryFields,
		&i.Funnels,
	)
	return i, err
}

const adminRefreshUserLogin = `-- name: AdminRefreshUserLogin :one
UPDATE admin_users
SET oauth_subject = COALESCE($1, oauth_subject),
    name = $2,
    picture_url = $3,
    provider = $4,
    last_login_at = now(),
    updated_at = now()
WHERE id = $5
RETURNING
    id,
    email,
    oauth_subject,
    role,
    enabled,
    name,
    picture_url,
    provider,
    last_login_at,
    created_at,
    updated_at
`

type AdminRefreshUserLoginParams struct {
	OauthSubject pgtype.Text `json:"oauth_subject"`
	Name         string      `json:"name"`
	PictureUrl   string      `json:"picture_url"`
	Provider     string      `json:"provider"`
	ID           uuid.UUID   `json:"id"`
}

type AdminRefreshUserLoginRow struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	OauthSubject pgtype.Text        `json:"oauth_subject"`
	Role         string             `json:"role"`
	Enabled      bool               `json:"enabled"`
	Name         string             `json:"name"`
	PictureUrl   string             `json:"picture_url"`
	Provider     string             `json:"provider"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
}

func (q *Queries) AdminRefreshUserLogin(ctx context.Context, arg AdminRefreshUserLoginParams) (AdminRefreshUserLoginRow, error) {
	row := q.db.QueryRow(ctx, adminRefreshUserLogin,
		arg.OauthSubject,
		arg.Name,
		arg.PictureUrl,
		arg.Provider,
		arg.ID,
	)
	var i AdminRefreshUserLoginRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.OauthSubject,
		&i.Role,
		&i.Enabled,
		&i.Name,
		&i.PictureUrl,
		&i.Provider,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminRegionHeatmap = `-- name: AdminRegionHeatmap :many
SELECT
    region_id,
    event_type,
    count(*)::bigint AS event_count
FROM events
WHERE events.project_id = $1
  AND real_ts >= $2
  AND real_ts <= $3
  AND ($4::text IS NULL OR event_type = $4)
  AND ($5::text IS NULL OR game_version = $5)
  AND ($6::text IS NULL OR build_channel = $6)
GROUP BY region_id, event_type
ORDER BY event_count DESC
`

type AdminRegionHeatmapParams struct {
	ProjectID    uuid.UUID   `json:"project_id"`
	RealTs       time.Time   `json:"real_ts"`
	RealTs_2     time.Time   `json:"real_ts_2"`
	EventType    pgtype.Text `json:"event_type"`
	GameVersion  pgtype.Text `json:"game_version"`
	BuildChannel pgtype.Text `json:"build_channel"`
}

type AdminRegionHeatmapRow struct {
	RegionID   string `json:"region_id"`
	EventType  string `json:"event_type"`
	EventCount int64  `json:"event_count"`
}

func (q *Queries) AdminRegionHeatmap(ctx context.Context, arg AdminRegionHeatmapParams) ([]AdminRegionHeatmapRow, error) {
	rows, err := q.db.Query(ctx, adminRegionHeatmap,
		arg.ProjectID,
		arg.RealTs,
		arg.RealTs_2,
		arg.EventType,
		arg.GameVersion,
		arg.BuildChannel,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminRegionHeatmapRow{}
	for rows.Next() {
		var i AdminRegionHeatmapRow
		if err := rows.Scan(&i.RegionID, &i.EventType, &i.EventCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminRegionHeatmapByField = `-- name: AdminRegionHeatmapByField :many
SELECT
    region_id,
    event_type,
    count(*)::bigint AS event_count
FROM event_fields filter_field
JOIN events ON events.id = filter_field.event_id
WHERE filter_field.project_id = $1
  AND filter_field.field_key = $4
  AND filter_field.value_type = $5
  AND (
      NOT $6::bool
      OR (filter_field.value_type = 'string' AND filter_field.string_value = $7::text)
      OR (filter_field.value_type = 'number' AND filter_field.number_value = $8::double precision)
      OR (filter_field.value_type = 'bool' AND filter_field.bool_value = $9::boolean)
  )
  AND events.project_id = $1
  AND real_ts >= $2
  AND real_ts <= $3
  AND ($10::text IS NULL OR event_type = $10)
  AND ($11::text IS NULL OR game_version = $11)
  AND ($12::text IS NULL OR build_channel = $12)
GROUP BY region_id, event_type
ORDER BY event_count DESC
`

type AdminRegionHeatmapByFieldParams struct {
	ProjectID        uuid.UUID   `json:"project_id"`
	RealTs           time.Time   `json:"real_ts"`
	RealTs_2         time.Time   `json:"real_ts_2"`
	FieldKey         string      `json:"field_key"`
	FieldValueType   string      `json:"field_value_type"`
	HasFieldValue    bool        `json:"has_field_value"`
	FieldStringValue string      `json:"field_string_value"`
	FieldNumberValue float64     `json:"field_number_value"`
	FieldBoolValue   bool        `json:"field_bool_value"`
	EventType        pgtype.Text `json:"event_type"`
	GameVersion      pgtype.Text `json:"game_version"`
	BuildChannel     pgtype.Text `json:"build_channel"`
}

type AdminRegionHeatmapByFieldRow struct {
	RegionID   string `json:"region_id"`
	EventType  string `json:"event_type"`
	EventCount int64  `json:"event_count"`
}

func (q *Queries) AdminRegionHeatmapByField(ctx context.Context, arg AdminRegionHeatmapByFieldParams) ([]AdminRegionHeatmapByFieldRow, error) {
	rows, err := q.db.Query(ctx, adminRegionHeatmapByField,
		arg.ProjectID,
		arg.RealTs,
		arg.RealTs_2,
		arg.FieldKey,
		arg.FieldValueType,
		arg.HasFieldValue,
		arg.FieldStringValue,
		arg.FieldNumberValue,
		arg.FieldBoolValue,
		arg.EventType,
		arg.GameVersion,
		arg.BuildChannel,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminRegionHeatmapByFieldRow{}
	for rows.Next() {
		var i AdminRegionHeatmapByFieldRow
		if err := rows.Scan(&i.RegionID, &i.EventType, &i.EventCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminRejectedEventGroups = `-- name: AdminRejectedEventGroups :many
SELECT
    re.event_type,
    re.reason_code,
    re.reason_message,
    re.game_version,
    re.build_channel,
    count(*)::bigint AS event_count,
    min(re.created_at)::timestamptz AS first_seen_at,
    max(re.created_at)::timestamptz AS last_seen_at,
    (
        SELECT sample.raw_event
        FROM rejected_events sample
        WHERE sample.project_id = re.project_id
          AND sample.event_type = re.event_type
          AND sample.reason_code = re.reason_code
          AND sample.game_version = re.game_version
        ORDER BY sample.created_at DESC
        LIMIT 1
    ) AS sample_event
FROM rejected_events re
WHERE re.project_id = $1
GROUP BY re.project_id, re.event_type, re.reason_code, re.reason_message, re.game_version, re.build_channel
ORDER BY last_seen_at DESC
`

type AdminRejectedEventGroupsRow struct {
	EventType     string          `json:"event_type"`
	ReasonCode    string          `json:"reason_code"`
	ReasonMessage string          `json:"reason_message"`
	GameVersion   string          `json:"game_version"`
	BuildChannel  string          `json:"build_channel"`
	EventCount    int64           `json:"event_count"`
	FirstSeenAt   time.Time       `json:"first_seen_at"`
	LastSeenAt    time.Time       `json:"last_seen_at"`
	SampleEvent   json.RawMessage `json:"sample_event"`
}

func (q *Queries) AdminRejectedEventGroups(ctx context.Context, projectID uuid.UUID) ([]AdminRejectedEventGroupsRow, error) {
	rows, err := q.db.Query(ctx, adminRejectedEventGroups, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminRejectedEventGroupsRow{}
	for rows.Next() {
		var i AdminRejectedEventGroupsRow
		if err := rows.Scan(
			&i.EventType,
			&i.ReasonCode,
			&i.ReasonMessage,
			&i.GameVersion,
			&i.BuildChannel,
			&i.EventCount,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.SampleEvent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminReportTrace = `-- name: AdminReportTrace :many
SELECT
    e.id,
    e.event_type,
    e.real_ts,
    e.game_time,
    e.region_id,
    e.zone_id,
    e.context,
    e.metrics,
    e.dimensions,
    e.payload
FROM bug_reports br
JOIN events report_event ON report_event.id = br.event_id
JOIN events e ON e.project_id = report_event.project_id
             AND e.player_id = report_event.player_id
             AND e.game_time >= report_event.game_time - $3
             AND e.game_time <= report_event.game_time + $3
WHERE br.project_id = $1
  AND br.report_id = $2
ORDER BY e.game_time ASC
`

type AdminReportTraceParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	ReportID  string    `json:"report_id"`
	GameTime  int64     `json:"game_time"`
}

type AdminReportTraceRow struct {
	ID         uuid.UUID       `json:"id"`
	EventType  string          `json:"event_type"`
	RealTs     time.Time       `json:"real_ts"`
	GameTime   int64           `json:"game_time"`
	RegionID   string          `json:"region_id"`
	ZoneID     string          `json:"zone_id"`
	Context    json.RawMessage `json:"context"`
	Metrics    json.RawMessage `json:"metrics"`
	Dimensions json.RawMessage `json:"dimensions"`
	Payload    json.RawMessage `json:"payload"`
}

func (q *Queries) AdminReportTrace(ctx context.Context, arg AdminReportTraceParams) ([]AdminReportTraceRow, error) {
	rows, err := q.db.Query(ctx, adminReportTrace, arg.ProjectID, arg.ReportID, arg.GameTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminReportTraceRow{}
	for rows.Next() {
		var i AdminReportTraceRow
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.RealTs,
			&i.GameTime,
			&i.RegionID,
			&i.ZoneID,
			&i.Context,
			&i.Metrics,
			&i.Dimensions,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminSetAgentAuthorizationEnabled = `-- name: AdminSetAgentAuthorizationEnabled :one
UPDATE agent_authorizations
SET enabled = $2,
    updated_at = now()
WHERE id = $1
RETURNING
    id,
    client_id,
    client_name,
    created_by_admin_user_id,
    all_projects,
    scopes,
    enabled,
    expires_at,
    activated_at,
    last_used_at,
    created_at,
    updated_at
`

type AdminSetAgentAuthorizationEnabledParams struct {
	ID      uuid.UUID `json:"id"`
	Enabled bool      `json:"enabled"`
}

type AdminSetAgentAuthorizationEnabledRow struct {
	ID                   uuid.UUID          `json:"id"`
	ClientID             string             `json:"client_id"`
	ClientName           string             `json:"client_name"`
	CreatedByAdminUserID pgtype.UUID        `json:"created_by_admin_user_id"`
	AllProjects          bool               `json:"all_projects"`
	Scopes               []string           `json:"scopes"`
	Enabled              bool               `json:"enabled"`
	ExpiresAt            time.Time          `json:"expires_at"`
	ActivatedAt          pgtype.Timestamptz `json:"activated_at"`
	LastUsedAt           pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt            time.Time          `json:"created_at"`
	UpdatedAt            time.Time          `json:"updated_at"`
}

func (q *Queries) AdminSetAgentAuthorizationEnabled(ctx context.Context, arg AdminSetAgentAuthorizationEnabledParams) (AdminSetAgentAuthorizationEnabledRow, error) {
	row := q.db.QueryRow(ctx, adminSetAgentAuthorizationEnabled, arg.ID, arg.Enabled)
	var i AdminSetAgentAuthorizationEnabledRow
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ClientName,
		&i.CreatedByAdminUserID,
		&i.AllProjects,
		&i.Scopes,
		&i.Enabled,
		&i.ExpiresAt,
		&i.ActivatedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminSetIngestTokenEnabled = `-- name: AdminSetIngestTokenEnabled :one
UPDATE ingest_tokens
SET enabled = $3
WHERE project_id = $1
  AND id = $2
RETURNING id, name, enabled, expires_at, last_used_at, created_at
`

type AdminSetIngestTokenEnabledParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	ID        uuid.UUID `json:"id"`
	Enabled   bool      `json:"enabled"`
}

type AdminSetIngestTokenEnabledRow struct {
	ID         uuid.UUID          `json:"id"`
	Name       string             `json:"name"`
	Enabled    bool               `json:"enabled"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt  time.Time          `json:"created_at"`
}

func (q *Queries) AdminSetIngestTokenEnabled(ctx context.Context, arg AdminSetIngestTokenEnabledParams) (AdminSetIngestTokenEnabledRow, error) {
	row := q.db.QueryRow(ctx, adminSetIngestTokenEnabled, arg.ProjectID, arg.ID, arg.Enabled)
	var i AdminSetIngestTokenEnabledRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Enabled,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const adminSetUserEnabled = `-- name: AdminSetUserEnabled :one
UPDATE admin_users
SET enabled = $2,
    updated_at = now()
WHERE id = $1
RETURNING
    id,
    email,
    oauth_subject,
    role,
    enabled,
    name,
    picture_url,
    provider,
    last_login_at,
    created_at,
    updated_at
`

type AdminSetUserEnabledParams struct {
	ID      uuid.UUID `json:"id"`
	Enabled bool      `json:"enabled"`
}

type AdminSetUserEnabledRow struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	OauthSubject pgtype.Text        `json:"oauth_subject"`
	Role         string             `json:"role"`
	Enabled      bool               `json:"enabled"`
	Name         string             `json:"name"`
	PictureUrl   string             `json:"picture_url"`
	Provider     string             `json:"provider"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
}

func (q *Queries) AdminSetUserEnabled(ctx context.Context, arg AdminSetUserEnabledParams) (AdminSetUserEnabledRow, error) {
	row := q.db.QueryRow(ctx, adminSetUserEnabled, arg.ID, arg.Enabled)
	var i AdminSetUserEnabledRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.OauthSubject,
		&i.Role,
		&i.Enabled,
		&i.Name,
		&i.PictureUrl,
		&i.Provider,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminSummary = `-- name: AdminSummary :one
SELECT
    count(*)::bigint AS event_count,
    count(DISTINCT player_id)::bigint AS player_count,
    count(*) FILTER (WHERE event_type = 'game_continue')::bigint AS session_count,
    count(*) FILTER (WHERE event_type = 'player_death')::bigint AS death_count,
    (
        SELECT count(*)::bigint
        FROM bug_reports br
        WHERE br.project_id = $1
          AND br.created_at >= $2
          AND br.created_at <= $3
    ) AS report_count
FROM events
WHERE events.project_id = $1
  AND real_ts >= $2
  AND real_ts <= $3
`

type AdminSummaryParams struct {
	ProjectID   uuid.UUID `json:"project_id"`
	CreatedAt   time.Time `json:"created_at"`
	CreatedAt_2 time.Time `json:"created_at_2"`
}

type AdminSummaryRow struct {
	EventCount   int64 `json:"event_count"`
	PlayerCount  int64 `json:"player_count"`
	SessionCount int64 `json:"session_count"`
	DeathCount   int64 `json:"death_count"`
	ReportCount  int64 `json:"report_count"`
}

func (q *Queries) AdminSummary(ctx context.Context, arg AdminSummaryParams) (AdminSummaryRow, error) {
	row := q.db.QueryRow(ctx, adminSummary, arg.ProjectID, arg.CreatedAt, arg.CreatedAt_2)
	var i AdminSummaryRow
	err := row.Scan(
		&i.EventCount,
		&i.PlayerCount,
		&i.SessionCount,
		&i.DeathCount,
		&i.ReportCount,
	)
	return i, err
}

const adminUpdateReport = `-- name: AdminUpdateReport :one
UPDATE bug_reports
SET status = $3,
    labels = $4,
    updated_at = now()
WHERE project_id = $1
  AND report_id = $2
RETURNING id, report_id, status, labels, updated_at
`

type AdminUpdateReportParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	ReportID  string    `json:"report_id"`
	Status    string    `json:"status"`
	Labels    []string  `json:"labels"`
}

type AdminUpdateReportRow struct {
	ID        uuid.UUID `json:"id"`
	ReportID  string    `json:"report_id"`
	Status    string    `json:"status"`
	Labels    []string  `json:"labels"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) AdminUpdateReport(ctx context.Context, arg AdminUpdateReportParams) (AdminUpdateReportRow, error) {
	row := q.db.QueryRow(ctx, adminUpdateReport,
		arg.ProjectID,
		arg.ReportID,
		arg.Status,
		arg.Labels,
	)
	var i AdminUpdateReportRow
	err := row.Scan(
		&i.ID,
		&i.ReportID,
		&i.Status,
		&i.Labels,
		&i.UpdatedAt,
	)
	return i, err
}

const adminUpsertProject = `-- name: AdminUpsertProject :one
INSERT INTO projects (
    project_key,
    display_name,
    validation_mode,
    ingest_config,
    retention_config,
    map_config,
    report_config,
    event_groups,
    query_fields,
    funnels
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
ON CONFLICT (project_key) DO UPDATE
SET display_name = EXCLUDED.display_name,
    validation_mode = EXCLUDED.validation_mode,
    ingest_config = EXCLUDED.ingest_config,
    retention_config = EXCLUDED.retention_config,
    map_config = EXCLUDED.map_config,
    report_config = EXCLUDED.report_config,
    event_groups = EXCLUDED.event_groups,
    query_fields = EXCLUDED.query_fields,
    funnels = EXCLUDED.funnels,
    updated_at = now()
RETURNING
    id,
    project_key,
    display_name,
    validation_mode,
    ingest_config,
    retention_config,
    map_config,
    report_config,
    event_groups,
    query_fields,
    funnels
`

type AdminUpsertProjectParams struct {
	ProjectKey      string          `json:"project_key"`
	DisplayName     string          `json:"display_name"`
	ValidationMode  string          `json:"validation_mode"`
	IngestConfig    json.RawMessage `json:"ingest_config"`
	RetentionConfig json.RawMessage `json:"retention_config"`
	MapConfig       json.RawMessage `json:"map_config"`
	ReportConfig    json.RawMessage `json:"report_config"`
	EventGroups     json.RawMessage `json:"event_groups"`
	QueryFields     json.RawMessage `json:"query_fields"`
	Funnels         json.RawMessage `json:"funnels"`
}

type AdminUpsertProjectRow struct {
	ID              uuid.UUID       `json:"id"`
	ProjectKey      string          `json:"project_key"`
	DisplayName     string          `json:"display_name"`
	ValidationMode  string          `json:"validation_mode"`
	IngestConfig    json.RawMessage `json:"ingest_config"`
	RetentionConfig json.RawMessage `json:"retention_config"`
	MapConfig       json.RawMessage `json:"map_config"`
	ReportConfig    json.RawMessage `json:"report_config"`
	EventGroups     json.RawMessage `json:"event_groups"`
	QueryFields     json.RawMessage `json:"query_fields"`
	Funnels         json.RawMessage `json:"funnels"`
}

func (q *Queries) AdminUpsertProject(ctx context.Context, arg AdminUpsertProjectParams) (AdminUpsertProjectRow, error) {
	row := q.db.QueryRow(ctx, adminUpsertProject,
		arg.ProjectKey,
		arg.DisplayName,
		arg.ValidationMode,
		arg.IngestConfig,
		arg.RetentionConfig,
		arg.MapConfig,
		arg.ReportConfig,
		arg.EventGroups,
		arg.QueryFields,
		arg.Funnels,
	)
	var i AdminUpsertProjectRow
	err := row.Scan(
		&i.ID,
		&i.ProjectKey,
		&i.DisplayName,
		&i.ValidationMode,
		&i.IngestConfig,
		&i.RetentionConfig,
		&i.MapConfig,
		&i.ReportConfig,
		&i.EventGroups,
		&i.QueryFields,
		&i.Funnels,
	)
	return i, err
}

const adminZoneHeatmap = `-- name: AdminZoneHeatmap :many
SELECT
    region_id,
    zone_id,
    round(coord_x / $4)::bigint AS grid_x,
    round(coord_z / $4)::bigint AS grid_z,
    event_type,
    count(*)::bigint AS event_count
FROM events
WHERE events.project_id = $1
  AND real_ts >= $2
  AND real_ts <= $3
  AND region_id = $5
  AND ($6::text IS NULL OR zone_id = $6)
  AND ($7::text IS NULL OR event_type = $7)
  AND ($8::text IS NULL OR game_version = $8)
  AND ($9::text IS NULL OR build_channel = $9)
GROUP BY region_id, zone_id, grid_x, grid_z, event_type
ORDER BY event_count DESC
`

type AdminZoneHeatmapParams struct {
	ProjectID    uuid.UUID   `json:"project_id"`
	RealTs       time.Time   `json:"real_ts"`
	RealTs_2     time.Time   `json:"real_ts_2"`
	CoordX       float64     `json:"coord_x"`
	RegionID     string      `json:"region_id"`
	ZoneID       pgtype.Text `json:"zone_id"`
	EventType    pgtype.Text `json:"event_type"`
	GameVersion  pgtype.Text `json:"game_version"`
	BuildChannel pgtype.Text `json:"build_channel"`
}

type AdminZoneHeatmapRow struct {
	RegionID   string `json:"region_id"`
	ZoneID     string `json:"zone_id"`
	GridX      int64  `json:"grid_x"`
	GridZ      int64  `json:"grid_z"`
	EventType  string `json:"event_type"`
	EventCount int64  `json:"event_count"`
}

func (q *Queries) AdminZoneHeatmap(ctx context.Context, arg AdminZoneHeatmapParams) ([]AdminZoneHeatmapRow, error) {
	rows, err := q.db.Query(ctx, adminZoneHeatmap,
		arg.ProjectID,
		arg.RealTs,
		arg.RealTs_2,
		arg.CoordX,
		arg.RegionID,
		arg.ZoneID,
		arg.EventType,
		arg.GameVersion,
		arg.BuildChannel,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminZoneHeatmapRow{}
	for rows.Next() {
		var i AdminZoneHeatmapRow
		if err := rows.Scan(
			&i.RegionID,
			&i.ZoneID,
			&i.GridX,
			&i.GridZ,
			&i.EventType,
			&i.EventCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminZoneHeatmapByField = `-- name: AdminZoneHeatmapByField :many
SELECT
    region_id,
    zone_id,
    round(coord_x / $4)::bigint AS grid_x,
    round(coord_z / $4)::bigint AS grid_z,
    event_type,
    count(*)::bigint AS event_count
FROM event_fields filter_field
JOIN events ON events.id = filter_field.event_id
WHERE filter_field.project_id = $1
  AND filter_field.field_key = $6
  AND filter_field.value_type = $7
  AND (
      NOT $8::bool
      OR (filter_field.value_type = 'string' AND filter_field.string_value = $9::text)
      OR (filter_field.value_type = 'number' AND filter_field.number_value = $10::double precision)
      OR (filter_field.value_type = 'bool' AND filter_field.bool_value = $11::boolean)
  )
  AND events.project_id = $1
  AND real_ts >= $2
  AND real_ts <= $3
  AND region_id = $5
  AND ($12::text IS NULL OR zone_id = $12)
  AND ($13::text IS NULL OR event_type = $13)
  AND ($14::text IS NULL OR game_version = $14)
  AND ($15::text IS NULL OR build_channel = $15)
GROUP BY region_id, zone_id, grid_x, grid_z, event_type
ORDER BY event_count DESC
`

type AdminZoneHeatmapByFieldParams struct {
	ProjectID        uuid.UUID   `json:"project_id"`
	RealTs           time.Time   `json:"real_ts"`
	RealTs_2         time.Time   `json:"real_ts_2"`
	CoordX           float64     `json:"coord_x"`
	RegionID         string      `json:"region_id"`
	FieldKey         string      `json:"field_key"`
	FieldValueType   string      `json:"field_value_type"`
	HasFieldValue    bool        `json:"has_field_value"`
	FieldStringValue string      `json:"field_string_value"`
	FieldNumberValue float64     `json:"field_number_value"`
	FieldBoolValue   bool        `json:"field_bool_value"`
	ZoneID           pgtype.Text `json:"zone_id"`
	EventType        pgtype.Text `json:"event_type"`
	GameVersion      pgtype.Text `json:"game_version"`
	BuildChannel     pgtype.Text `json:"build_channel"`
}

type AdminZoneHeatmapByFieldRow struct {
	RegionID   string `json:"region_id"`
	ZoneID     string `json:"zone_id"`
	GridX      int64  `json:"grid_x"`
	GridZ      int64  `json:"grid_z"`
	EventType  string `json:"event_type"`
	EventCount int64  `json:"event_count"`
}

func (q *Queries) AdminZoneHeatmapByField(ctx context.Context, arg AdminZoneHeatmapByFieldParams) ([]AdminZoneHeatmapByFieldRow, error) {
	rows, err := q.db.Query(ctx, adminZoneHeatmapByField,
		arg.ProjectID,
		arg.RealTs,
		arg.RealTs_2,
		arg.CoordX,
		arg.RegionID,
		arg.FieldKey,
		arg.FieldValueType,
		arg.HasFieldValue,
		arg.FieldStringValue,
		arg.FieldNumberValue,
		arg.FieldBoolValue,
		arg.ZoneID,
		arg.EventType,
		arg.GameVersion,
		arg.BuildChannel,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminZoneHeatmapByFieldRow{}
	for rows.Next() {
		var i AdminZoneHeatmapByFieldRow
		if err := rows.Scan(
			&i.RegionID,
			&i.ZoneID,
			&i.GridX,
			&i.GridZ,
			&i.EventType,
			&i.EventCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mCPActivateAgentAuthorization = `-- name: MCPActivateAgentAuthorization :one
UPDATE agent_authorizations
SET token_hash = $2,
    activated_at = now(),
    updated_at = now()
WHERE id = $1
  AND token_hash IS NULL
  AND enabled = true
  AND expires_at > now()
RETURNING
    id,
    client_id,
    client_name,
    created_by_admin_user_id,
    all_projects,
    scopes,
    enabled,
    expires_at,
    activated_at,
    last_used_at,
    created_at,
    updated_at
`

type MCPActivateAgentAuthorizationParams struct {
	ID        uuid.UUID   `json:"id"`
	TokenHash pgtype.Text `json:"token_hash"`
}

type MCPActivateAgentAuthorizationRow struct {
	ID                   uuid.UUID          `json:"id"`
	ClientID             string             `json:"client_id"`
	ClientName           string             `json:"client_name"`
	CreatedByAdminUserID pgtype.UUID        `json:"created_by_admin_user_id"`
	AllProjects          bool               `json:"all_projects"`
	Scopes               []string           `json:"scopes"`
	Enabled              bool               `json:"enabled"`
	ExpiresAt            time.Time          `json:"expires_at"`
	ActivatedAt          pgtype.Timestamptz `json:"activated_at"`
	LastUsedAt           pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt            time.Time          `json:"created_at"`
	UpdatedAt            time.Time          `json:"updated_at"`
}

func (q *Queries) MCPActivateAgentAuthorization(ctx context.Context, arg MCPActivateAgentAuthorizationParams) (MCPActivateAgentAuthorizationRow, error) {
	row := q.db.QueryRow(ctx, mCPActivateAgentAuthorization, arg.ID, arg.TokenHash)
	var i MCPActivateAgentAuthorizationRow
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ClientName,
		&i.CreatedByAdminUserID,
		&i.AllProjects,
		&i.Scopes,
		&i.Enabled,
		&i.ExpiresAt,
		&i.ActivatedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const mCPCleanupExpiredOAuthCodes = `-- name: MCPCleanupExpiredOAuthCodes :exec
DELETE FROM mcp_oauth_codes
WHERE expires_at < now()
`

func (q *Queries) MCPCleanupExpiredOAuthCodes(ctx context.Context) error {
	_, err := q.db.Exec(ctx, mCPCleanupExpiredOAuthCodes)
	return err
}

const mCPCleanupExpiredOAuthState = `-- name: MCPCleanupExpiredOAuthState :exec
DELETE FROM agent_authorizations aa
WHERE aa.token_hash IS NULL
  AND EXISTS (
      SELECT 1
      FROM mcp_oauth_codes code
      WHERE code.agent_authorization_id = aa.id
        AND code.expires_at < now()
  )
`

func (q *Queries) MCPCleanupExpiredOAuthState(ctx context.Context) error {
	_, err := q.db.Exec(ctx, mCPCleanupExpiredOAuthState)
	return err
}

const mCPConsumeOAuthCode = `-- name: MCPConsumeOAuthCode :one
UPDATE mcp_oauth_codes
SET consumed_at = now()
WHERE code_hash = $1
  AND client_id = $2
  AND redirect_uri = $3
  AND resource = $4
  AND consumed_at IS NULL
  AND expires_at > now()
RETURNING
    client_id,
    redirect_uri,
    code_challenge,
    code_challenge_method,
    resource,
    scopes,
    admin_user_id,
    agent_authorization_id,
    expires_at,
    consumed_at,
    created_at
`

type MCPConsumeOAuthCodeParams struct {
	CodeHash    string `json:"code_hash"`
	ClientID    string `json:"client_id"`
	RedirectUri string `json:"redirect_uri"`
	Resource    string `json:"resource"`
}

type MCPConsumeOAuthCodeRow struct {
	ClientID             string             `json:"client_id"`
	RedirectUri          string             `json:"redirect_uri"`
	CodeChallenge        string             `json:"code_challenge"`
	CodeChallengeMethod  string             `json:"code_challenge_method"`
	Resource             string             `json:"resource"`
	Scopes               []string           `json:"scopes"`
	AdminUserID          uuid.UUID          `json:"admin_user_id"`
	AgentAuthorizationID uuid.UUID          `json:"agent_authorization_id"`
	ExpiresAt            time.Time          `json:"expires_at"`
	ConsumedAt           pgtype.Timestamptz `json:"consumed_at"`
	CreatedAt            time.Time          `json:"created_at"`
}

func (q *Queries) MCPConsumeOAuthCode(ctx context.Context, arg MCPConsumeOAuthCodeParams) (MCPConsumeOAuthCodeRow, error) {
	row := q.db.QueryRow(ctx, mCPConsumeOAuthCode,
		arg.CodeHash,
		arg.ClientID,
		arg.RedirectUri,
		arg.Resource,
	)
	var i MCPConsumeOAuthCodeRow
	err := row.Scan(
		&i.ClientID,
		&i.RedirectUri,
		&i.CodeChallenge,
		&i.CodeChallengeMethod,
		&i.Resource,
		&i.Scopes,
		&i.AdminUserID,
		&i.AgentAuthorizationID,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const mCPCreateAgentAuthorization = `-- name: MCPCreateAgentAuthorization :one
INSERT INTO agent_authorizations (
    client_id,
    client_name,
    created_by_admin_user_id,
    all_projects,
    scopes,
    expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING
    id,
    client_id,
    client_name,
    created_by_admin_user_id,
    all_projects,
    scopes,
    enabled,
    expires_at,
    activated_at,
    last_used_at,
    created_at,
    updated_at
`

type MCPCreateAgentAuthorizationParams struct {
	ClientID             string      `json:"client_id"`
	ClientName           string      `json:"client_name"`
	CreatedByAdminUserID pgtype.UUID `json:"created_by_admin_user_id"`
	AllProjects          bool        `json:"all_projects"`
	Scopes               []string    `json:"scopes"`
	ExpiresAt            time.Time   `json:"expires_at"`
}

type MCPCreateAgentAuthorizationRow struct {
	ID                   uuid.UUID          `json:"id"`
	ClientID             string             `json:"client_id"`
	ClientName           string             `json:"client_name"`
	CreatedByAdminUserID pgtype.UUID        `json:"created_by_admin_user_id"`
	AllProjects          bool               `json:"all_projects"`
	Scopes               []string           `json:"scopes"`
	Enabled              bool               `json:"enabled"`
	ExpiresAt            time.Time          `json:"expires_at"`
	ActivatedAt          pgtype.Timestamptz `json:"activated_at"`
	LastUsedAt           pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt            time.Time          `json:"created_at"`
	UpdatedAt            time.Time          `json:"updated_at"`
}

func (q *Queries) MCPCreateAgentAuthorization(ctx context.Context, arg MCPCreateAgentAuthorizationParams) (MCPCreateAgentAuthorizationRow, error) {
	row := q.db.QueryRow(ctx, mCPCreateAgentAuthorization,
		arg.ClientID,
		arg.ClientName,
		arg.CreatedByAdminUserID,
		arg.AllProjects,
		arg.Scopes,
		arg.ExpiresAt,
	)
	var i MCPCreateAgentAuthorizationRow
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ClientName,
		&i.CreatedByAdminUserID,
		&i.AllProjects,
		&i.Scopes,
		&i.Enabled,
		&i.ExpiresAt,
		&i.ActivatedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const mCPCreateAgentAuthorizationProject = `-- name: MCPCreateAgentAuthorizationProject :exec
INSERT INTO agent_authorization_projects (
    agent_authorization_id,
    project_id
) VALUES (
    $1, $2
)
`

type MCPCreateAgentAuthorizationProjectParams struct {
	AgentAuthorizationID uuid.UUID `json:"agent_authorization_id"`
	ProjectID            uuid.UUID `json:"project_id"`
}

func (q *Queries) MCPCreateAgentAuthorizationProject(ctx context.Context, arg MCPCreateAgentAuthorizationProjectParams) error {
	_, err := q.db.Exec(ctx, mCPCreateAgentAuthorizationProject, arg.AgentAuthorizationID, arg.ProjectID)
	return err
}

const mCPCreateOAuthCode = `-- name: MCPCreateOAuthCode :exec
INSERT INTO mcp_oauth_codes (
    code_hash,
    client_id,
    redirect_uri,
    code_challenge,
    code_challenge_method,
    resource,
    scopes,
    admin_user_id,
    agent_authorization_id,
    expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
`

type MCPCreateOAuthCodeParams struct {
	CodeHash             string    `json:"code_hash"`
	ClientID             string    `json:"client_id"`
	RedirectUri          string    `json:"redirect_uri"`
	CodeChallenge        string    `json:"code_challenge"`
	CodeChallengeMethod  string    `json:"code_challenge_method"`
	Resource             string    `json:"resource"`
	Scopes               []string  `json:"scopes"`
	AdminUserID          uuid.UUID `json:"admin_user_id"`
	AgentAuthorizationID uuid.UUID `json:"agent_authorization_id"`
	ExpiresAt            time.Time `json:"expires_at"`
}

func (q *Queries) MCPCreateOAuthCode(ctx context.Context, arg MCPCreateOAuthCodeParams) error {
	_, err := q.db.Exec(ctx, mCPCreateOAuthCode,
		arg.CodeHash,
		arg.ClientID,
		arg.RedirectUri,
		arg.CodeChallenge,
		arg.CodeChallengeMethod,
		arg.Resource,
		arg.Scopes,
		arg.AdminUserID,
		arg.AgentAuthorizationID,
		arg.ExpiresAt,
	)
	return err
}

const mCPGetOAuthClient = `-- name: MCPGetOAuthClient :one
SELECT
    client_id,
    client_name,
    redirect_uris,
    client_uri,
    logo_uri,
    created_at,
    updated_at
FROM mcp_oauth_clients
WHERE client_id = $1
`

func (q *Queries) MCPGetOAuthClient(ctx context.Context, clientID string) (McpOauthClient, error) {
	row := q.db.QueryRow(ctx, mCPGetOAuthClient, clientID)
	var i McpOauthClient
	err := row.Scan(
		&i.ClientID,
		&i.ClientName,
		&i.RedirectUris,
		&i.ClientUri,
		&i.LogoUri,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const mCPListAgentAuthorizationProjects = `-- name: MCPListAgentAuthorizationProjects :many
SELECT
    p.id,
    p.project_key
FROM agent_authorization_projects aap
JOIN projects p ON p.id = aap.project_id
WHERE aap.agent_authorization_id = $1
ORDER BY p.project_key ASC
`

type MCPListAgentAuthorizationProjectsRow struct {
	ID         uuid.UUID `json:"id"`
	ProjectKey string    `json:"project_key"`
}

func (q *Queries) MCPListAgentAuthorizationProjects(ctx context.Context, agentAuthorizationID uuid.UUID) ([]MCPListAgentAuthorizationProjectsRow, error) {
	rows, err := q.db.Query(ctx, mCPListAgentAuthorizationProjects, agentAuthorizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MCPListAgentAuthorizationProjectsRow{}
	for rows.Next() {
		var i MCPListAgentAuthorizationProjectsRow
		if err := rows.Scan(&i.ID, &i.ProjectKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mCPUpsertOAuthClient = `-- name: MCPUpsertOAuthClient :one
INSERT INTO mcp_oauth_clients (
    client_id,
    client_name,
    redirect_uris,
    client_uri,
    logo_uri
) VALUES (
    $1, $2, $3, $4, $5
)
ON CONFLICT (client_id) DO UPDATE
SET client_name = EXCLUDED.client_name,
    redirect_uris = EXCLUDED.redirect_uris,
    client_uri = EXCLUDED.client_uri,
    logo_uri = EXCLUDED.logo_uri,
    updated_at = now()
RETURNING
    client_id,
    client_name,
    redirect_uris,
    client_uri,
    logo_uri,
    created_at,
    updated_at
`

type MCPUpsertOAuthClientParams struct {
	ClientID     string   `json:"client_id"`
	ClientName   string   `json:"client_name"`
	RedirectUris []string `json:"redirect_uris"`
	ClientUri    string   `json:"client_uri"`
	LogoUri      string   `json:"logo_uri"`
}

func (q *Queries) MCPUpsertOAuthClient(ctx context.Context, arg MCPUpsertOAuthClientParams) (McpOauthClient, error) {
	row := q.db.QueryRow(ctx, mCPUpsertOAuthClient,
		arg.ClientID,
		arg.ClientName,
		arg.RedirectUris,
		arg.ClientUri,
		arg.LogoUri,
	)
	var i McpOauthClient
	err := row.Scan(
		&i.ClientID,
		&i.ClientName,
		&i.RedirectUris,
		&i.ClientUri,
		&i.LogoUri,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const mCPValidateAgentToken = `-- name: MCPValidateAgentToken :one
UPDATE agent_authorizations aa
SET last_used_at = now()
FROM admin_users au
WHERE aa.token_hash = $1
  AND aa.enabled = true
  AND aa.expires_at > now()
  AND aa.created_by_admin_user_id IS NOT NULL
  AND au.id = aa.created_by_admin_user_id
  AND au.enabled = true
RETURNING
    aa.id,
    aa.client_id,
    aa.client_name,
    aa.created_by_admin_user_id,
    aa.all_projects,
    aa.scopes,
    aa.enabled,
    aa.expires_at,
    aa.activated_at,
    aa.last_used_at,
    aa.created_at,
    aa.updated_at
`

type MCPValidateAgentTokenRow struct {
	ID                   uuid.UUID          `json:"id"`
	ClientID             string             `json:"client_id"`
	ClientName           string             `json:"client_name"`
	CreatedByAdminUserID pgtype.UUID        `json:"created_by_admin_user_id"`
	AllProjects          bool               `json:"all_projects"`
	Scopes               []string           `json:"scopes"`
	Enabled              bool               `json:"enabled"`
	ExpiresAt            time.Time          `json:"expires_at"`
	ActivatedAt          pgtype.Timestamptz `json:"activated_at"`
	LastUsedAt           pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt            time.Time          `json:"created_at"`
	UpdatedAt            time.Time          `json:"updated_at"`
}

func (q *Queries) MCPValidateAgentToken(ctx context.Context, tokenHash pgtype.Text) (MCPValidateAgentTokenRow, error) {
	row := q.db.QueryRow(ctx, mCPValidateAgentToken, tokenHash)
	var i MCPValidateAgentTokenRow
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ClientName,
		&i.CreatedByAdminUserID,
		&i.AllProjects,
		&i.Scopes,
		&i.Enabled,
		&i.ExpiresAt,
		&i.ActivatedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
