// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package dbq

import (
	"context"

	"github.com/google/uuid"
)

const getProjectIDByTokenHash = `-- name: GetProjectIDByTokenHash :one
UPDATE ingest_tokens
SET last_used_at = now()
WHERE token_hash = $1
  AND enabled = true
  AND (expires_at IS NULL OR expires_at > now())
RETURNING project_id
`

func (q *Queries) GetProjectIDByTokenHash(ctx context.Context, tokenHash string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getProjectIDByTokenHash, tokenHash)
	var project_id uuid.UUID
	err := row.Scan(&project_id)
	return project_id, err
}
