// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ingest.sql

package dbq

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countRecentBugReportsByPlayer = `-- name: CountRecentBugReportsByPlayer :one
SELECT count(*)::bigint
FROM bug_reports br
JOIN events e ON e.id = br.event_id
WHERE br.project_id = $1
  AND e.player_id = $2
  AND br.created_at > now() - make_interval(secs => $3)
`

type CountRecentBugReportsByPlayerParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	PlayerID  uuid.UUID `json:"player_id"`
	Secs      float64   `json:"secs"`
}

func (q *Queries) CountRecentBugReportsByPlayer(ctx context.Context, arg CountRecentBugReportsByPlayerParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentBugReportsByPlayer, arg.ProjectID, arg.PlayerID, arg.Secs)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createBatch = `-- name: CreateBatch :one
INSERT INTO batches (
    project_id,
    batch_id,
    accepted_count,
    rejected_count,
    request_meta
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, accepted_count, rejected_count
`

type CreateBatchParams struct {
	ProjectID     uuid.UUID       `json:"project_id"`
	BatchID       string          `json:"batch_id"`
	AcceptedCount int32           `json:"accepted_count"`
	RejectedCount int32           `json:"rejected_count"`
	RequestMeta   json.RawMessage `json:"request_meta"`
}

type CreateBatchRow struct {
	ID            uuid.UUID `json:"id"`
	AcceptedCount int32     `json:"accepted_count"`
	RejectedCount int32     `json:"rejected_count"`
}

func (q *Queries) CreateBatch(ctx context.Context, arg CreateBatchParams) (CreateBatchRow, error) {
	row := q.db.QueryRow(ctx, createBatch,
		arg.ProjectID,
		arg.BatchID,
		arg.AcceptedCount,
		arg.RejectedCount,
		arg.RequestMeta,
	)
	var i CreateBatchRow
	err := row.Scan(&i.ID, &i.AcceptedCount, &i.RejectedCount)
	return i, err
}

const createBugReport = `-- name: CreateBugReport :one
INSERT INTO bug_reports (
    project_id,
    report_id,
    event_id,
    mood,
    mood_label,
    notes_preview,
    screenshot_object_key,
    screenshot_storage_error
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, screenshot_object_key
`

type CreateBugReportParams struct {
	ProjectID              uuid.UUID   `json:"project_id"`
	ReportID               string      `json:"report_id"`
	EventID                uuid.UUID   `json:"event_id"`
	Mood                   int32       `json:"mood"`
	MoodLabel              string      `json:"mood_label"`
	NotesPreview           string      `json:"notes_preview"`
	ScreenshotObjectKey    pgtype.Text `json:"screenshot_object_key"`
	ScreenshotStorageError pgtype.Text `json:"screenshot_storage_error"`
}

type CreateBugReportRow struct {
	ID                  uuid.UUID   `json:"id"`
	ScreenshotObjectKey pgtype.Text `json:"screenshot_object_key"`
}

func (q *Queries) CreateBugReport(ctx context.Context, arg CreateBugReportParams) (CreateBugReportRow, error) {
	row := q.db.QueryRow(ctx, createBugReport,
		arg.ProjectID,
		arg.ReportID,
		arg.EventID,
		arg.Mood,
		arg.MoodLabel,
		arg.NotesPreview,
		arg.ScreenshotObjectKey,
		arg.ScreenshotStorageError,
	)
	var i CreateBugReportRow
	err := row.Scan(&i.ID, &i.ScreenshotObjectKey)
	return i, err
}

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (
    project_id,
    batch_db_id,
    player_id,
    event_type,
    real_ts,
    game_time,
    region_id,
    zone_id,
    coord_x,
    coord_y,
    coord_z,
    game_version,
    build_channel,
    commit_sha,
    platform,
    context,
    metrics,
    dimensions,
    payload,
    event_json,
    validation_errors
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21
)
RETURNING id
`

type CreateEventParams struct {
	ProjectID        uuid.UUID       `json:"project_id"`
	BatchDbID        pgtype.UUID     `json:"batch_db_id"`
	PlayerID         uuid.UUID       `json:"player_id"`
	EventType        string          `json:"event_type"`
	RealTs           time.Time       `json:"real_ts"`
	GameTime         int64           `json:"game_time"`
	RegionID         string          `json:"region_id"`
	ZoneID           string          `json:"zone_id"`
	CoordX           float64         `json:"coord_x"`
	CoordY           float64         `json:"coord_y"`
	CoordZ           float64         `json:"coord_z"`
	GameVersion      string          `json:"game_version"`
	BuildChannel     string          `json:"build_channel"`
	CommitSHA        string          `json:"commit_sha"`
	Platform         string          `json:"platform"`
	Context          json.RawMessage `json:"context"`
	Metrics          json.RawMessage `json:"metrics"`
	Dimensions       json.RawMessage `json:"dimensions"`
	Payload          json.RawMessage `json:"payload"`
	EventJson        json.RawMessage `json:"event_json"`
	ValidationErrors json.RawMessage `json:"validation_errors"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.ProjectID,
		arg.BatchDbID,
		arg.PlayerID,
		arg.EventType,
		arg.RealTs,
		arg.GameTime,
		arg.RegionID,
		arg.ZoneID,
		arg.CoordX,
		arg.CoordY,
		arg.CoordZ,
		arg.GameVersion,
		arg.BuildChannel,
		arg.CommitSHA,
		arg.Platform,
		arg.Context,
		arg.Metrics,
		arg.Dimensions,
		arg.Payload,
		arg.EventJson,
		arg.ValidationErrors,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createEventField = `-- name: CreateEventField :exec
INSERT INTO event_fields (
    event_id,
    project_id,
    field_key,
    value_type,
    string_value,
    number_value,
    bool_value
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
ON CONFLICT (event_id, field_key) DO UPDATE
SET value_type = EXCLUDED.value_type,
    string_value = EXCLUDED.string_value,
    number_value = EXCLUDED.number_value,
    bool_value = EXCLUDED.bool_value
`

type CreateEventFieldParams struct {
	EventID     uuid.UUID     `json:"event_id"`
	ProjectID   uuid.UUID     `json:"project_id"`
	FieldKey    string        `json:"field_key"`
	ValueType   string        `json:"value_type"`
	StringValue pgtype.Text   `json:"string_value"`
	NumberValue pgtype.Float8 `json:"number_value"`
	BoolValue   pgtype.Bool   `json:"bool_value"`
}

func (q *Queries) CreateEventField(ctx context.Context, arg CreateEventFieldParams) error {
	_, err := q.db.Exec(ctx, createEventField,
		arg.EventID,
		arg.ProjectID,
		arg.FieldKey,
		arg.ValueType,
		arg.StringValue,
		arg.NumberValue,
		arg.BoolValue,
	)
	return err
}

const getBatchByProjectAndBatchID = `-- name: GetBatchByProjectAndBatchID :one
SELECT id, accepted_count, rejected_count
FROM batches
WHERE project_id = $1
  AND batch_id = $2
`

type GetBatchByProjectAndBatchIDParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	BatchID   string    `json:"batch_id"`
}

type GetBatchByProjectAndBatchIDRow struct {
	ID            uuid.UUID `json:"id"`
	AcceptedCount int32     `json:"accepted_count"`
	RejectedCount int32     `json:"rejected_count"`
}

func (q *Queries) GetBatchByProjectAndBatchID(ctx context.Context, arg GetBatchByProjectAndBatchIDParams) (GetBatchByProjectAndBatchIDRow, error) {
	row := q.db.QueryRow(ctx, getBatchByProjectAndBatchID, arg.ProjectID, arg.BatchID)
	var i GetBatchByProjectAndBatchIDRow
	err := row.Scan(&i.ID, &i.AcceptedCount, &i.RejectedCount)
	return i, err
}

const getProjectByKey = `-- name: GetProjectByKey :one
SELECT id, project_key, display_name, validation_mode, query_fields
FROM projects
WHERE project_key = $1
`

type GetProjectByKeyRow struct {
	ID             uuid.UUID       `json:"id"`
	ProjectKey     string          `json:"project_key"`
	DisplayName    string          `json:"display_name"`
	ValidationMode string          `json:"validation_mode"`
	QueryFields    json.RawMessage `json:"query_fields"`
}

func (q *Queries) GetProjectByKey(ctx context.Context, projectKey string) (GetProjectByKeyRow, error) {
	row := q.db.QueryRow(ctx, getProjectByKey, projectKey)
	var i GetProjectByKeyRow
	err := row.Scan(
		&i.ID,
		&i.ProjectKey,
		&i.DisplayName,
		&i.ValidationMode,
		&i.QueryFields,
	)
	return i, err
}
