// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbq

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AdminUser struct {
	ID           uuid.UUID   `json:"id"`
	Email        string      `json:"email"`
	OauthSubject pgtype.Text `json:"oauth_subject"`
	Role         string      `json:"role"`
	Enabled      bool        `json:"enabled"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
}

type Batch struct {
	ID            uuid.UUID       `json:"id"`
	ProjectID     uuid.UUID       `json:"project_id"`
	BatchID       string          `json:"batch_id"`
	AcceptedCount int32           `json:"accepted_count"`
	RejectedCount int32           `json:"rejected_count"`
	RequestMeta   json.RawMessage `json:"request_meta"`
	CreatedAt     time.Time       `json:"created_at"`
}

type BugReport struct {
	ID                     uuid.UUID   `json:"id"`
	ProjectID              uuid.UUID   `json:"project_id"`
	ReportID               string      `json:"report_id"`
	EventID                uuid.UUID   `json:"event_id"`
	Status                 string      `json:"status"`
	Labels                 []string    `json:"labels"`
	Mood                   int32       `json:"mood"`
	MoodLabel              string      `json:"mood_label"`
	NotesPreview           string      `json:"notes_preview"`
	ScreenshotObjectKey    pgtype.Text `json:"screenshot_object_key"`
	ScreenshotStorageError pgtype.Text `json:"screenshot_storage_error"`
	CreatedAt              time.Time   `json:"created_at"`
	UpdatedAt              time.Time   `json:"updated_at"`
}

type Event struct {
	ID               uuid.UUID       `json:"id"`
	ProjectID        uuid.UUID       `json:"project_id"`
	BatchDbID        pgtype.UUID     `json:"batch_db_id"`
	CommanderID      uuid.UUID       `json:"commander_id"`
	EventType        string          `json:"event_type"`
	RealTs           time.Time       `json:"real_ts"`
	GameTime         int64           `json:"game_time"`
	SystemID         string          `json:"system_id"`
	ZoneID           string          `json:"zone_id"`
	CoordX           float64         `json:"coord_x"`
	CoordY           float64         `json:"coord_y"`
	CoordZ           float64         `json:"coord_z"`
	GameVersion      string          `json:"game_version"`
	BuildChannel     string          `json:"build_channel"`
	Platform         string          `json:"platform"`
	Context          json.RawMessage `json:"context"`
	Metrics          json.RawMessage `json:"metrics"`
	Dimensions       json.RawMessage `json:"dimensions"`
	Payload          json.RawMessage `json:"payload"`
	EventJson        json.RawMessage `json:"event_json"`
	ValidationErrors json.RawMessage `json:"validation_errors"`
	CreatedAt        time.Time       `json:"created_at"`
}

type EventField struct {
	EventID     uuid.UUID     `json:"event_id"`
	ProjectID   uuid.UUID     `json:"project_id"`
	FieldKey    string        `json:"field_key"`
	ValueType   string        `json:"value_type"`
	StringValue pgtype.Text   `json:"string_value"`
	NumberValue pgtype.Float8 `json:"number_value"`
	BoolValue   pgtype.Bool   `json:"bool_value"`
}

type IngestToken struct {
	ID         uuid.UUID          `json:"id"`
	ProjectID  uuid.UUID          `json:"project_id"`
	Name       string             `json:"name"`
	TokenHash  string             `json:"token_hash"`
	Enabled    bool               `json:"enabled"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt  time.Time          `json:"created_at"`
}

type Project struct {
	ID              uuid.UUID       `json:"id"`
	ProjectKey      string          `json:"project_key"`
	DisplayName     string          `json:"display_name"`
	ValidationMode  string          `json:"validation_mode"`
	IngestConfig    json.RawMessage `json:"ingest_config"`
	RetentionConfig json.RawMessage `json:"retention_config"`
	MapConfig       json.RawMessage `json:"map_config"`
	ReportConfig    json.RawMessage `json:"report_config"`
	EventGroups     json.RawMessage `json:"event_groups"`
	QueryFields     json.RawMessage `json:"query_fields"`
	CreatedAt       time.Time       `json:"created_at"`
	UpdatedAt       time.Time       `json:"updated_at"`
}

type ReportNote struct {
	ID          uuid.UUID   `json:"id"`
	ReportID    uuid.UUID   `json:"report_id"`
	AdminUserID pgtype.UUID `json:"admin_user_id"`
	Note        string      `json:"note"`
	CreatedAt   time.Time   `json:"created_at"`
}
