// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbq

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AdminCreateIngestToken(ctx context.Context, arg AdminCreateIngestTokenParams) (AdminCreateIngestTokenRow, error)
	AdminCreateReportNote(ctx context.Context, arg AdminCreateReportNoteParams) (AdminCreateReportNoteRow, error)
	AdminEventTypes(ctx context.Context, projectID uuid.UUID) ([]AdminEventTypesRow, error)
	AdminFunnelCounts(ctx context.Context, arg AdminFunnelCountsParams) (AdminFunnelCountsRow, error)
	AdminGetReport(ctx context.Context, arg AdminGetReportParams) (AdminGetReportRow, error)
	AdminListEvents(ctx context.Context, arg AdminListEventsParams) ([]AdminListEventsRow, error)
	AdminListEventsByField(ctx context.Context, arg AdminListEventsByFieldParams) ([]AdminListEventsByFieldRow, error)
	AdminListIngestTokens(ctx context.Context, projectID uuid.UUID) ([]AdminListIngestTokensRow, error)
	AdminListProjects(ctx context.Context) ([]AdminListProjectsRow, error)
	AdminListReportNotes(ctx context.Context, reportID uuid.UUID) ([]AdminListReportNotesRow, error)
	AdminListReports(ctx context.Context, arg AdminListReportsParams) ([]AdminListReportsRow, error)
	AdminListReportsByLabel(ctx context.Context, arg AdminListReportsByLabelParams) ([]AdminListReportsByLabelRow, error)
	AdminPlayerTrace(ctx context.Context, arg AdminPlayerTraceParams) ([]AdminPlayerTraceRow, error)
	AdminProjectSettings(ctx context.Context, projectKey string) (AdminProjectSettingsRow, error)
	AdminReportTrace(ctx context.Context, arg AdminReportTraceParams) ([]AdminReportTraceRow, error)
	AdminSetIngestTokenEnabled(ctx context.Context, arg AdminSetIngestTokenEnabledParams) (AdminSetIngestTokenEnabledRow, error)
	AdminSummary(ctx context.Context, arg AdminSummaryParams) (AdminSummaryRow, error)
	AdminSystemHeatmap(ctx context.Context, arg AdminSystemHeatmapParams) ([]AdminSystemHeatmapRow, error)
	AdminSystemHeatmapByField(ctx context.Context, arg AdminSystemHeatmapByFieldParams) ([]AdminSystemHeatmapByFieldRow, error)
	AdminUpdateReport(ctx context.Context, arg AdminUpdateReportParams) (AdminUpdateReportRow, error)
	AdminUpsertProject(ctx context.Context, arg AdminUpsertProjectParams) (AdminUpsertProjectRow, error)
	AdminZoneHeatmap(ctx context.Context, arg AdminZoneHeatmapParams) ([]AdminZoneHeatmapRow, error)
	AdminZoneHeatmapByField(ctx context.Context, arg AdminZoneHeatmapByFieldParams) ([]AdminZoneHeatmapByFieldRow, error)
	CountRecentBugReportsByPlayer(ctx context.Context, arg CountRecentBugReportsByPlayerParams) (int64, error)
	CreateBatch(ctx context.Context, arg CreateBatchParams) (CreateBatchRow, error)
	CreateBugReport(ctx context.Context, arg CreateBugReportParams) (CreateBugReportRow, error)
	CreateEvent(ctx context.Context, arg CreateEventParams) (uuid.UUID, error)
	CreateEventField(ctx context.Context, arg CreateEventFieldParams) error
	GetBatchByProjectAndBatchID(ctx context.Context, arg GetBatchByProjectAndBatchIDParams) (GetBatchByProjectAndBatchIDRow, error)
	GetProjectByKey(ctx context.Context, projectKey string) (GetProjectByKeyRow, error)
	GetProjectIDByTokenHash(ctx context.Context, tokenHash string) (uuid.UUID, error)
}

var _ Querier = (*Queries)(nil)
