// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbq

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AdminAcceptInvitation(ctx context.Context, arg AdminAcceptInvitationParams) (AdminAcceptInvitationRow, error)
	AdminAcknowledgeRejectedEvents(ctx context.Context, projectID uuid.UUID) error
	AdminCountActiveRejectionGroups(ctx context.Context, projectID uuid.UUID) (int64, error)
	AdminCountEnabledUsers(ctx context.Context) (int64, error)
	AdminCountUsers(ctx context.Context) (int64, error)
	AdminCreateIngestToken(ctx context.Context, arg AdminCreateIngestTokenParams) (AdminCreateIngestTokenRow, error)
	AdminCreateInvitation(ctx context.Context, arg AdminCreateInvitationParams) (AdminCreateInvitationRow, error)
	AdminCreateReportNote(ctx context.Context, arg AdminCreateReportNoteParams) (AdminCreateReportNoteRow, error)
	AdminCreateUser(ctx context.Context, arg AdminCreateUserParams) (AdminCreateUserRow, error)
	AdminDeleteInvitation(ctx context.Context, id uuid.UUID) (AdminDeleteInvitationRow, error)
	AdminEventTypes(ctx context.Context, projectID uuid.UUID) ([]AdminEventTypesRow, error)
	AdminGetReport(ctx context.Context, arg AdminGetReportParams) (AdminGetReportRow, error)
	AdminGetUserByEmail(ctx context.Context, email string) (AdminGetUserByEmailRow, error)
	AdminGetUserByID(ctx context.Context, id uuid.UUID) (AdminGetUserByIDRow, error)
	AdminGetUserBySubject(ctx context.Context, oauthSubject pgtype.Text) (AdminGetUserBySubjectRow, error)
	AdminListActiveInvitations(ctx context.Context) ([]AdminListActiveInvitationsRow, error)
	AdminListAgentAuthorizations(ctx context.Context) ([]AdminListAgentAuthorizationsRow, error)
	AdminListEvents(ctx context.Context, arg AdminListEventsParams) ([]AdminListEventsRow, error)
	AdminListEventsByField(ctx context.Context, arg AdminListEventsByFieldParams) ([]AdminListEventsByFieldRow, error)
	AdminListIngestTokens(ctx context.Context, projectID uuid.UUID) ([]AdminListIngestTokensRow, error)
	AdminListProjects(ctx context.Context) ([]AdminListProjectsRow, error)
	AdminListReportNotes(ctx context.Context, reportID uuid.UUID) ([]AdminListReportNotesRow, error)
	AdminListReports(ctx context.Context, arg AdminListReportsParams) ([]AdminListReportsRow, error)
	AdminListReportsByLabel(ctx context.Context, arg AdminListReportsByLabelParams) ([]AdminListReportsByLabelRow, error)
	AdminListUsers(ctx context.Context) ([]AdminListUsersRow, error)
	AdminPlayerTrace(ctx context.Context, arg AdminPlayerTraceParams) ([]AdminPlayerTraceRow, error)
	AdminProjectSettings(ctx context.Context, projectKey string) (AdminProjectSettingsRow, error)
	AdminRefreshUserLogin(ctx context.Context, arg AdminRefreshUserLoginParams) (AdminRefreshUserLoginRow, error)
	AdminRegionHeatmap(ctx context.Context, arg AdminRegionHeatmapParams) ([]AdminRegionHeatmapRow, error)
	AdminRegionHeatmapByField(ctx context.Context, arg AdminRegionHeatmapByFieldParams) ([]AdminRegionHeatmapByFieldRow, error)
	AdminRejectedEventGroups(ctx context.Context, projectID uuid.UUID) ([]AdminRejectedEventGroupsRow, error)
	AdminReportTrace(ctx context.Context, arg AdminReportTraceParams) ([]AdminReportTraceRow, error)
	AdminSetAgentAuthorizationEnabled(ctx context.Context, arg AdminSetAgentAuthorizationEnabledParams) (AdminSetAgentAuthorizationEnabledRow, error)
	AdminSetIngestTokenEnabled(ctx context.Context, arg AdminSetIngestTokenEnabledParams) (AdminSetIngestTokenEnabledRow, error)
	AdminSetUserEnabled(ctx context.Context, arg AdminSetUserEnabledParams) (AdminSetUserEnabledRow, error)
	AdminSummary(ctx context.Context, arg AdminSummaryParams) (AdminSummaryRow, error)
	AdminUpdateReport(ctx context.Context, arg AdminUpdateReportParams) (AdminUpdateReportRow, error)
	AdminUpsertProject(ctx context.Context, arg AdminUpsertProjectParams) (AdminUpsertProjectRow, error)
	AdminZoneHeatmap(ctx context.Context, arg AdminZoneHeatmapParams) ([]AdminZoneHeatmapRow, error)
	AdminZoneHeatmapByField(ctx context.Context, arg AdminZoneHeatmapByFieldParams) ([]AdminZoneHeatmapByFieldRow, error)
	CountRecentBugReportsByPlayer(ctx context.Context, arg CountRecentBugReportsByPlayerParams) (int64, error)
	CreateBatch(ctx context.Context, arg CreateBatchParams) (CreateBatchRow, error)
	CreateBugReport(ctx context.Context, arg CreateBugReportParams) (CreateBugReportRow, error)
	CreateEvent(ctx context.Context, arg CreateEventParams) (uuid.UUID, error)
	CreateEventField(ctx context.Context, arg CreateEventFieldParams) error
	CreateRejectedEvent(ctx context.Context, arg CreateRejectedEventParams) error
	GetBatchByProjectAndBatchID(ctx context.Context, arg GetBatchByProjectAndBatchIDParams) (GetBatchByProjectAndBatchIDRow, error)
	GetBugReportByProjectAndReportID(ctx context.Context, arg GetBugReportByProjectAndReportIDParams) (GetBugReportByProjectAndReportIDRow, error)
	GetProjectByKey(ctx context.Context, projectKey string) (GetProjectByKeyRow, error)
	GetProjectIDByTokenHash(ctx context.Context, tokenHash string) (uuid.UUID, error)
	MCPActivateAgentAuthorization(ctx context.Context, arg MCPActivateAgentAuthorizationParams) (MCPActivateAgentAuthorizationRow, error)
	MCPCleanupExpiredOAuthCodes(ctx context.Context) error
	MCPCleanupExpiredOAuthState(ctx context.Context) error
	MCPConsumeOAuthCode(ctx context.Context, arg MCPConsumeOAuthCodeParams) (MCPConsumeOAuthCodeRow, error)
	MCPCreateAgentAuthorization(ctx context.Context, arg MCPCreateAgentAuthorizationParams) (MCPCreateAgentAuthorizationRow, error)
	MCPCreateAgentAuthorizationProject(ctx context.Context, arg MCPCreateAgentAuthorizationProjectParams) error
	MCPCreateOAuthCode(ctx context.Context, arg MCPCreateOAuthCodeParams) error
	MCPGetOAuthClient(ctx context.Context, clientID string) (McpOauthClient, error)
	MCPListAgentAuthorizationProjects(ctx context.Context, agentAuthorizationID uuid.UUID) ([]MCPListAgentAuthorizationProjectsRow, error)
	MCPUpsertOAuthClient(ctx context.Context, arg MCPUpsertOAuthClientParams) (McpOauthClient, error)
	MCPValidateAgentToken(ctx context.Context, tokenHash pgtype.Text) (MCPValidateAgentTokenRow, error)
	PruneRejectedEvents(ctx context.Context, arg PruneRejectedEventsParams) error
}

var _ Querier = (*Queries)(nil)
